// Code generated by abstraction-idl from abstraction-router/router.thrift. DO NOT EDIT.

#![allow(dead_code)]

use std::collections::BTreeMap;

// An opaque payload is bytes the contract forbids us to reinterpret, and String
// would refuse to hold one that is not UTF-8 rather than carry it back out.
pub type Raw = Vec<u8>;

const HEX: &[u8; 16] = b"0123456789abcdef";

fn esc_byte(out: &mut Vec<u8>, c: u8) {
    match c {
        b'"' => out.extend_from_slice(b"\\\""),
        b'\\' => out.extend_from_slice(b"\\\\"),
        0x08 => out.extend_from_slice(b"\\b"),
        0x0c => out.extend_from_slice(b"\\f"),
        b'\n' => out.extend_from_slice(b"\\n"),
        b'\r' => out.extend_from_slice(b"\\r"),
        b'\t' => out.extend_from_slice(b"\\t"),
        _ if c < 0x20 => {
            out.extend_from_slice(b"\\u00");
            out.push(HEX[(c >> 4) as usize]);
            out.push(HEX[(c & 0x0F) as usize]);
        }
        _ => out.push(c),
    }
}

pub fn num(out: &mut Vec<u8>, n: i64) {
    out.extend_from_slice(n.to_string().as_bytes());
}

pub fn pad(out: &mut Vec<u8>, depth: i32) {
    for _ in 0..depth * 2 {
        out.push(b' ');
    }
}

pub fn strs(out: &mut Vec<u8>, v: &[String], depth: i32) {
    if v.is_empty() {
        out.extend_from_slice(b"[]");
        return;
    }
    out.extend_from_slice(b"[\n");
    for (i, s) in v.iter().enumerate() {
        pad(out, depth + 1);
        esc(out, s);
        if i + 1 < v.len() {
            out.push(b',');
        }
        out.push(b'\n');
    }
    pad(out, depth);
    out.push(b']');
}

fn ws(c: u8) -> bool {
    c == b' ' || c == b'\t' || c == b'\n' || c == b'\r'
}

pub fn raw(out: &mut Vec<u8>, b: &[u8], depth: i32) {
    let mut depth = depth;
    let mut i = 0;
    while i < b.len() {
        let c = b[i];
        if ws(c) {
            i += 1;
        } else if c == b'"' {
            let mut j = i + 1;
            while j < b.len() {
                if b[j] == b'\\' {
                    j += 2;
                    continue;
                }
                if b[j] == b'"' {
                    j += 1;
                    break;
                }
                j += 1;
            }
            out.extend_from_slice(&b[i..j]);
            i = j;
        } else if c == b'{' || c == b'[' {
            out.push(c);
            i += 1;
            let mut j = i;
            while j < b.len() && ws(b[j]) {
                j += 1;
            }
            if j < b.len() && (b[j] == b'}' || b[j] == b']') {
                out.push(b[j]);
                i = j + 1;
            } else {
                depth += 1;
                out.push(b'\n');
                pad(out, depth);
            }
        } else if c == b'}' || c == b']' {
            depth -= 1;
            out.push(b'\n');
            pad(out, depth);
            out.push(c);
            i += 1;
        } else if c == b',' {
            out.extend_from_slice(b",\n");
            pad(out, depth);
            i += 1;
        } else if c == b':' {
            out.extend_from_slice(b": ");
            i += 1;
        } else {
            out.push(c);
            i += 1;
        }
    }
}

// A BTreeMap<String, _> walks its keys in String's Ord, which compares the
// UTF-8 bytes — the order the definition declares. Nothing sorts here.
pub fn rawmap(out: &mut Vec<u8>, m: &BTreeMap<String, Raw>, depth: i32) {
    if m.is_empty() {
        out.extend_from_slice(b"{}");
        return;
    }
    out.extend_from_slice(b"{\n");
    for (i, (k, v)) in m.iter().enumerate() {
        pad(out, depth + 1);
        esc(out, k);
        out.extend_from_slice(b": ");
        raw(out, v, depth + 1);
        if i + 1 < m.len() {
            out.push(b',');
        }
        out.push(b'\n');
    }
    pad(out, depth);
    out.push(b'}');
}

pub fn esc(out: &mut Vec<u8>, s: &str) {
    out.push(b'"');
    for c in s.as_bytes() {
        esc_byte(out, *c);
    }
    out.push(b'"');
}

pub fn enc_list<T>(out: &mut Vec<u8>, v: &[T], depth: i32, enc: fn(&mut Vec<u8>, &T, i32)) {
    if v.is_empty() {
        out.extend_from_slice(b"[]");
        return;
    }
    out.extend_from_slice(b"[\n");
    for (i, x) in v.iter().enumerate() {
        pad(out, depth + 1);
        enc(out, x, depth + 1);
        if i + 1 < v.len() {
            out.push(b',');
        }
        out.push(b'\n');
    }
    pad(out, depth);
    out.push(b']');
}

pub const VERDICTS: [&str; 6] = ["resident", "would-load", "unservable", "not-here", "unparseable", "unauthorised"];

#[derive(Default)]
pub struct HostAllowance {
    pub hosts: Vec<String>,
}

#[derive(Default)]
pub struct PickRequest {
    pub model: String,
    pub fresh: bool,
    pub allowed: Option<HostAllowance>,
}

#[derive(Default)]
pub struct Caller {
    pub user_description: String,
    pub path_description: String,
}

#[derive(Default)]
pub struct Observation {
    pub caller: Caller,
    pub took_ms: i64,
    pub cache_age_ms: i64,
}

#[derive(Default)]
pub struct Alias {
    pub host: String,
    pub name: String,
    pub resident: bool,
    pub servable: bool,
}

#[derive(Default)]
pub struct Family {
    pub family: String,
    pub names: Vec<Alias>,
}

#[derive(Default)]
pub struct ModelsSnapshot {
    pub observation: Observation,
    pub models: Vec<Family>,
}

#[derive(Default)]
pub struct HostState {
    pub host: String,
    pub base: String,
    pub up: bool,
    pub why: String,
    pub installed: i64,
    pub resident: Vec<String>,
    pub servable: bool,
}

#[derive(Default)]
pub struct Ask {
    pub at: String,
    pub caller: String,
    pub user: String,
    pub model: String,
    pub family: String,
    pub verdict: String,
    pub host: String,
}

#[derive(Default)]
pub struct HostsSnapshot {
    pub observation: Observation,
    pub hosts: Vec<HostState>,
    pub doubled: Vec<String>,
    pub asked: Vec<Ask>,
}

#[derive(Default)]
pub struct Decision {
    pub asked: String,
    pub family: String,
    pub verdict: String,
    pub host: String,
    pub model: String,
    pub endpoint: String,
    pub installed_on: Vec<String>,
    pub authorised: Option<HostAllowance>,
    pub withheld: Vec<String>,
    pub loads: i64,
    pub why: String,
}

#[derive(Default)]
pub struct PickResult {
    pub observation: Observation,
    pub decision: Decision,
}

#[derive(Default)]
pub struct OARouterModelsArguments {
    pub fresh: bool,
}

#[derive(Default)]
pub struct OARouterHostsArguments {
    pub fresh: bool,
}

#[derive(Default)]
pub struct OARouterPickArguments {
    pub request: PickRequest,
}

#[derive(Default)]
pub struct OAServiceFrame {
    pub version: i32,
    pub service: String,
    pub method: String,
    pub arguments: Raw,
}

#[derive(Default)]
pub struct OAServiceReply {
    pub version: i32,
    pub service: String,
    pub method: String,
    pub ok: bool,
    pub payload: Raw,
}

#[derive(Default)]
pub struct OAServiceError {
    pub code: String,
    pub message: String,
}

#[derive(Default)]
pub struct OARouterModelsResult {
    pub value: ModelsSnapshot,
}

#[derive(Default)]
pub struct OARouterHostsResult {
    pub value: HostsSnapshot,
}

#[derive(Default)]
pub struct OARouterPickResult {
    pub value: PickResult,
}

pub fn enc_hostallowance(out: &mut Vec<u8>, v: &HostAllowance, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "hosts");
    out.extend_from_slice(b": ");
    strs(out, &v.hosts, depth + 1);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_pickrequest(out: &mut Vec<u8>, v: &PickRequest, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "model");
    out.extend_from_slice(b": ");
    esc(out, &v.model);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "fresh");
    out.extend_from_slice(b": ");
    out.extend_from_slice(if v.fresh { b"true" } else { b"false" });
    if v.allowed.is_some() {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "allowed");
        out.extend_from_slice(b": ");
        enc_hostallowance(out, v.allowed.as_ref().unwrap(), depth + 1);
    }
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_caller(out: &mut Vec<u8>, v: &Caller, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "user_description");
    out.extend_from_slice(b": ");
    esc(out, &v.user_description);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "path_description");
    out.extend_from_slice(b": ");
    esc(out, &v.path_description);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_observation(out: &mut Vec<u8>, v: &Observation, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "caller");
    out.extend_from_slice(b": ");
    enc_caller(out, &v.caller, depth + 1);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "took_ms");
    out.extend_from_slice(b": ");
    num(out, v.took_ms);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "cache_age_ms");
    out.extend_from_slice(b": ");
    num(out, v.cache_age_ms);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_alias(out: &mut Vec<u8>, v: &Alias, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "host");
    out.extend_from_slice(b": ");
    esc(out, &v.host);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "name");
    out.extend_from_slice(b": ");
    esc(out, &v.name);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "resident");
    out.extend_from_slice(b": ");
    out.extend_from_slice(if v.resident { b"true" } else { b"false" });
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "servable");
    out.extend_from_slice(b": ");
    out.extend_from_slice(if v.servable { b"true" } else { b"false" });
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_family(out: &mut Vec<u8>, v: &Family, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "family");
    out.extend_from_slice(b": ");
    esc(out, &v.family);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "names");
    out.extend_from_slice(b": ");
    enc_list(out, &v.names, depth + 1, enc_alias);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_modelssnapshot(out: &mut Vec<u8>, v: &ModelsSnapshot, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "observation");
    out.extend_from_slice(b": ");
    enc_observation(out, &v.observation, depth + 1);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "models");
    out.extend_from_slice(b": ");
    enc_list(out, &v.models, depth + 1, enc_family);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_hoststate(out: &mut Vec<u8>, v: &HostState, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "host");
    out.extend_from_slice(b": ");
    esc(out, &v.host);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "base");
    out.extend_from_slice(b": ");
    esc(out, &v.base);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "up");
    out.extend_from_slice(b": ");
    out.extend_from_slice(if v.up { b"true" } else { b"false" });
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "why");
    out.extend_from_slice(b": ");
    esc(out, &v.why);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "installed");
    out.extend_from_slice(b": ");
    num(out, v.installed);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "resident");
    out.extend_from_slice(b": ");
    strs(out, &v.resident, depth + 1);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "servable");
    out.extend_from_slice(b": ");
    out.extend_from_slice(if v.servable { b"true" } else { b"false" });
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_ask(out: &mut Vec<u8>, v: &Ask, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "at");
    out.extend_from_slice(b": ");
    esc(out, &write_timestamp(&v.at));
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "caller");
    out.extend_from_slice(b": ");
    esc(out, &v.caller);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "user");
    out.extend_from_slice(b": ");
    esc(out, &v.user);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "model");
    out.extend_from_slice(b": ");
    esc(out, &v.model);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "family");
    out.extend_from_slice(b": ");
    esc(out, &v.family);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "verdict");
    out.extend_from_slice(b": ");
    esc(out, &v.verdict);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "host");
    out.extend_from_slice(b": ");
    esc(out, &v.host);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_hostssnapshot(out: &mut Vec<u8>, v: &HostsSnapshot, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "observation");
    out.extend_from_slice(b": ");
    enc_observation(out, &v.observation, depth + 1);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "hosts");
    out.extend_from_slice(b": ");
    enc_list(out, &v.hosts, depth + 1, enc_hoststate);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "doubled");
    out.extend_from_slice(b": ");
    strs(out, &v.doubled, depth + 1);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "asked");
    out.extend_from_slice(b": ");
    enc_list(out, &v.asked, depth + 1, enc_ask);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_decision(out: &mut Vec<u8>, v: &Decision, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "asked");
    out.extend_from_slice(b": ");
    esc(out, &v.asked);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "family");
    out.extend_from_slice(b": ");
    esc(out, &v.family);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "verdict");
    out.extend_from_slice(b": ");
    esc(out, &v.verdict);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "host");
    out.extend_from_slice(b": ");
    esc(out, &v.host);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "model");
    out.extend_from_slice(b": ");
    esc(out, &v.model);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "endpoint");
    out.extend_from_slice(b": ");
    esc(out, &v.endpoint);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "installed_on");
    out.extend_from_slice(b": ");
    strs(out, &v.installed_on, depth + 1);
    if v.authorised.is_some() {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "authorised");
        out.extend_from_slice(b": ");
        enc_hostallowance(out, v.authorised.as_ref().unwrap(), depth + 1);
    }
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "withheld");
    out.extend_from_slice(b": ");
    strs(out, &v.withheld, depth + 1);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "loads");
    out.extend_from_slice(b": ");
    num(out, v.loads);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "why");
    out.extend_from_slice(b": ");
    esc(out, &v.why);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_pickresult(out: &mut Vec<u8>, v: &PickResult, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "observation");
    out.extend_from_slice(b": ");
    enc_observation(out, &v.observation, depth + 1);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "decision");
    out.extend_from_slice(b": ");
    enc_decision(out, &v.decision, depth + 1);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oaroutermodelsarguments(out: &mut Vec<u8>, v: &OARouterModelsArguments, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "fresh");
    out.extend_from_slice(b": ");
    out.extend_from_slice(if v.fresh { b"true" } else { b"false" });
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oarouterhostsarguments(out: &mut Vec<u8>, v: &OARouterHostsArguments, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "fresh");
    out.extend_from_slice(b": ");
    out.extend_from_slice(if v.fresh { b"true" } else { b"false" });
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oarouterpickarguments(out: &mut Vec<u8>, v: &OARouterPickArguments, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "request");
    out.extend_from_slice(b": ");
    enc_pickrequest(out, &v.request, depth + 1);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oaserviceframe(out: &mut Vec<u8>, v: &OAServiceFrame, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "version");
    out.extend_from_slice(b": ");
    num(out, v.version as i64);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "service");
    out.extend_from_slice(b": ");
    esc(out, &v.service);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "method");
    out.extend_from_slice(b": ");
    esc(out, &v.method);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "arguments");
    out.extend_from_slice(b": ");
    out.extend_from_slice(&v.arguments);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oaservicereply(out: &mut Vec<u8>, v: &OAServiceReply, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "version");
    out.extend_from_slice(b": ");
    num(out, v.version as i64);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "service");
    out.extend_from_slice(b": ");
    esc(out, &v.service);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "method");
    out.extend_from_slice(b": ");
    esc(out, &v.method);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "ok");
    out.extend_from_slice(b": ");
    out.extend_from_slice(if v.ok { b"true" } else { b"false" });
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "payload");
    out.extend_from_slice(b": ");
    out.extend_from_slice(&v.payload);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oaserviceerror(out: &mut Vec<u8>, v: &OAServiceError, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "code");
    out.extend_from_slice(b": ");
    esc(out, &v.code);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "message");
    out.extend_from_slice(b": ");
    esc(out, &v.message);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oaroutermodelsresult(out: &mut Vec<u8>, v: &OARouterModelsResult, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "value");
    out.extend_from_slice(b": ");
    enc_modelssnapshot(out, &v.value, depth + 1);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oarouterhostsresult(out: &mut Vec<u8>, v: &OARouterHostsResult, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "value");
    out.extend_from_slice(b": ");
    enc_hostssnapshot(out, &v.value, depth + 1);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oarouterpickresult(out: &mut Vec<u8>, v: &OARouterPickResult, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "value");
    out.extend_from_slice(b": ");
    enc_pickresult(out, &v.value, depth + 1);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn encode(v: &PickRequest) -> Vec<u8> {
    let mut out = Vec::new();
    enc_pickrequest(&mut out, v, 0);
    out.push(b'\n');
    out
}

const DEPTH_LIMIT: i32 = 64;

#[derive(Debug)]
pub struct Refusal {
    pub word: &'static str,
    pub offset: usize,
}

impl std::fmt::Display for Refusal {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "refused: {} at byte {}", self.word, self.offset)
    }
}

impl std::error::Error for Refusal {}

fn append_rune(out: &mut Vec<u8>, cp: u32) {
    if cp < 0x80 {
        out.push(cp as u8);
    } else if cp < 0x800 {
        out.push(0xC0 | (cp >> 6) as u8);
        out.push(0x80 | (cp & 0x3F) as u8);
    } else if cp < 0x10000 {
        out.push(0xE0 | (cp >> 12) as u8);
        out.push(0x80 | ((cp >> 6) & 0x3F) as u8);
        out.push(0x80 | (cp & 0x3F) as u8);
    } else {
        out.push(0xF0 | (cp >> 18) as u8);
        out.push(0x80 | ((cp >> 12) & 0x3F) as u8);
        out.push(0x80 | ((cp >> 6) & 0x3F) as u8);
        out.push(0x80 | (cp & 0x3F) as u8);
    }
}

struct Reader<'a> {
    buf: &'a [u8],
    pos: usize,
    depth: i32,
}

impl<'a> Reader<'a> {
    fn refuse<T>(&self, word: &'static str) -> Result<T, Refusal> {
        Err(Refusal { word, offset: self.pos })
    }

    fn at(&self) -> u8 {
        if self.pos < self.buf.len() { self.buf[self.pos] } else { 0 }
    }

    fn skip_ws(&mut self) {
        while self.pos < self.buf.len() && ws(self.buf[self.pos]) {
            self.pos += 1;
        }
    }

    fn enter(&mut self) -> Result<(), Refusal> {
        self.depth += 1;
        if self.depth > DEPTH_LIMIT {
            return self.refuse("depth_exceeded");
        }
        Ok(())
    }

    fn string(&mut self) -> Result<String, Refusal> {
        if self.at() != b'"' {
            return self.refuse("wrong_type");
        }
        self.pos += 1;
        let mut out: Vec<u8> = Vec::new();
        loop {
            if self.pos >= self.buf.len() {
                return self.refuse("malformed");
            }
            let c = self.buf[self.pos];
            if c == b'"' {
                self.pos += 1;
                return match String::from_utf8(out) {
                    Ok(s) => Ok(s),
                    Err(_) => self.refuse("bad_string"),
                };
            }
            if c < 0x20 {
                return self.refuse("bad_string");
            }
            if c == b'\\' {
                self.escape(&mut out)?;
            } else {
                out.push(c);
                self.pos += 1;
            }
        }
    }

    fn escape(&mut self, out: &mut Vec<u8>) -> Result<(), Refusal> {
        self.pos += 1;
        if self.pos >= self.buf.len() {
            return self.refuse("malformed");
        }
        let c = self.buf[self.pos];
        self.pos += 1;
        match c {
            b'"' | b'\\' | b'/' => out.push(c),
            b'b' => out.push(0x08),
            b'f' => out.push(0x0c),
            b'n' => out.push(b'\n'),
            b'r' => out.push(b'\r'),
            b't' => out.push(b'\t'),
            b'u' => {
                let mut u = self.hex4()?;
                if (0xDC00..=0xDFFF).contains(&u) {
                    return self.refuse("bad_string");
                }
                if (0xD800..=0xDBFF).contains(&u) {
                    if self.pos + 1 >= self.buf.len()
                        || self.buf[self.pos] != b'\\'
                        || self.buf[self.pos + 1] != b'u'
                    {
                        return self.refuse("bad_string");
                    }
                    self.pos += 2;
                    let low = self.hex4()?;
                    if !(0xDC00..=0xDFFF).contains(&low) {
                        return self.refuse("bad_string");
                    }
                    u = 0x10000 + ((u - 0xD800) << 10) + (low - 0xDC00);
                }
                append_rune(out, u);
            }
            _ => return self.refuse("bad_string"),
        }
        Ok(())
    }

    fn hex4(&mut self) -> Result<u32, Refusal> {
        if self.pos + 4 > self.buf.len() {
            return self.refuse("bad_string");
        }
        let mut u: u32 = 0;
        for i in 0..4 {
            let c = self.buf[self.pos + i];
            let d = match c {
                b'0'..=b'9' => c - b'0',
                b'a'..=b'f' => c - b'a' + 10,
                b'A'..=b'F' => c - b'A' + 10,
                _ => return self.refuse("bad_string"),
            };
            u = u << 4 | d as u32;
        }
        self.pos += 4;
        Ok(u)
    }

    fn integer(&mut self, low: i64, high: i64) -> Result<i64, Refusal> {
        let c = self.at();
        if c != b'-' && !c.is_ascii_digit() {
            return self.refuse("wrong_type");
        }
        let negative = c == b'-';
        if negative {
            self.pos += 1;
        }
        if !self.at().is_ascii_digit() {
            return self.refuse("malformed");
        }
        let mut u: u64 = 0;
        if self.at() == b'0' {
            self.pos += 1;
        } else {
            while self.at().is_ascii_digit() {
                if u > 922337203685477580 {
                    return self.refuse("number_spelling");
                }
                u = u * 10 + (self.at() - b'0') as u64;
                self.pos += 1;
            }
        }
        let after = self.at();
        if after == b'.' || after == b'e' || after == b'E' || after.is_ascii_digit() {
            return self.refuse("number_spelling");
        }
        if negative && u == 0 {
            return self.refuse("number_spelling");
        }
        let n = if negative {
            if u > 1u64 << 63 {
                return self.refuse("number_spelling");
            }
            if u == 1u64 << 63 { i64::MIN } else { -(u as i64) }
        } else {
            if u > i64::MAX as u64 {
                return self.refuse("number_spelling");
            }
            u as i64
        };
        if n < low || n > high {
            return self.refuse("number_spelling");
        }
        Ok(n)
    }

    fn boolean(&mut self) -> Result<bool, Refusal> {
        match self.at() {
            b't' => {
                self.literal(b"true")?;
                Ok(true)
            }
            b'f' => {
                self.literal(b"false")?;
                Ok(false)
            }
            _ => self.refuse("wrong_type"),
        }
    }

    fn literal(&mut self, word: &[u8]) -> Result<(), Refusal> {
        if self.pos + word.len() > self.buf.len() || &self.buf[self.pos..self.pos + word.len()] != word {
            return self.refuse("malformed");
        }
        self.pos += word.len();
        Ok(())
    }

    fn str_list(&mut self) -> Result<Vec<String>, Refusal> {
        if self.at() != b'[' {
            return self.refuse("wrong_type");
        }
        self.enter()?;
        self.pos += 1;
        let mut out = Vec::new();
        self.skip_ws();
        if self.at() != b']' {
            loop {
                self.skip_ws();
                out.push(self.string()?);
                self.skip_ws();
                if self.at() != b',' {
                    break;
                }
                self.pos += 1;
            }
        }
        if self.at() != b']' {
            return self.refuse("malformed");
        }
        self.pos += 1;
        self.depth -= 1;
        Ok(out)
    }

    fn raw_map(&mut self) -> Result<BTreeMap<String, Raw>, Refusal> {
        if self.at() != b'{' {
            return self.refuse("wrong_type");
        }
        self.enter()?;
        self.pos += 1;
        let mut out = BTreeMap::new();
        self.skip_ws();
        if self.at() != b'}' {
            loop {
                self.skip_ws();
                if self.at() != b'"' {
                    return self.refuse("malformed");
                }
                let k = self.string()?;
                if out.contains_key(&k) {
                    return self.refuse("duplicate_key");
                }
                self.skip_ws();
                if self.at() != b':' {
                    return self.refuse("malformed");
                }
                self.pos += 1;
                self.skip_ws();
                let v = self.raw_value()?;
                out.insert(k, v);
                self.skip_ws();
                if self.at() != b',' {
                    break;
                }
                self.pos += 1;
            }
        }
        if self.at() != b'}' {
            return self.refuse("malformed");
        }
        self.pos += 1;
        self.depth -= 1;
        Ok(out)
    }

    fn raw_value(&mut self) -> Result<Raw, Refusal> {
        let start = self.pos;
        self.skip_value()?;
        Ok(self.buf[start..self.pos].to_vec())
    }

    fn skip_value(&mut self) -> Result<(), Refusal> {
        let c = self.at();
        match c {
            b'"' => self.skip_string(),
            b'{' | b'[' => self.skip_container(),
            b't' => self.literal(b"true"),
            b'f' => self.literal(b"false"),
            b'n' => self.literal(b"null"),
            b'-' => self.skip_number(),
            _ if c.is_ascii_digit() => self.skip_number(),
            _ => self.refuse("malformed"),
        }
    }

    // An opaque value is validated and carried, never interpreted. Its syntax is
    // the record's own — the same string reader, so an escape, a control byte or
    // a lone surrogate is judged identically at any depth — and what it is free
    // to spell, it keeps: the bytes between these two offsets are what a writer
    // re-emits. A number is walked, never converted, so a value no host type
    // holds survives the reader that carried it.
    fn skip_string(&mut self) -> Result<(), Refusal> {
        self.string()?;
        Ok(())
    }

    fn some_digits(&mut self) -> Result<(), Refusal> {
        let mut n = 0;
        while self.at().is_ascii_digit() {
            self.pos += 1;
            n += 1;
        }
        if n == 0 {
            return self.refuse("number_spelling");
        }
        Ok(())
    }

    fn skip_number(&mut self) -> Result<(), Refusal> {
        if self.at() == b'-' {
            self.pos += 1;
        }
        match self.at() {
            b'0' => self.pos += 1,
            c if c.is_ascii_digit() => {
                while self.at().is_ascii_digit() {
                    self.pos += 1;
                }
            }
            _ => return self.refuse("number_spelling"),
        }
        if self.at() == b'.' {
            self.pos += 1;
            self.some_digits()?;
        }
        if self.at() == b'e' || self.at() == b'E' {
            self.pos += 1;
            if self.at() == b'+' || self.at() == b'-' {
                self.pos += 1;
            }
            self.some_digits()?;
        }
        Ok(())
    }

    fn skip_container(&mut self) -> Result<(), Refusal> {
        let opener = self.at();
        let shut = if opener == b'{' { b'}' } else { b']' };
        self.enter()?;
        self.pos += 1;
        self.skip_ws();
        let mut seen: BTreeMap<String, bool> = BTreeMap::new();
        if self.at() != shut {
            loop {
                self.skip_ws();
                if opener == b'{' {
                    if self.at() != b'"' {
                        return self.refuse("malformed");
                    }
                    let k = self.string()?;
                    if seen.insert(k, true).is_some() {
                        return self.refuse("duplicate_key");
                    }
                    self.skip_ws();
                    if self.at() != b':' {
                        return self.refuse("malformed");
                    }
                    self.pos += 1;
                    self.skip_ws();
                }
                self.skip_value()?;
                self.skip_ws();
                if self.at() != b',' {
                    break;
                }
                self.pos += 1;
            }
        }
        if self.at() != shut {
            return self.refuse("malformed");
        }
        self.pos += 1;
        self.depth -= 1;
        Ok(())
    }
}

fn decode_list<T>(
    r: &mut Reader,
    elem: fn(&mut Reader) -> Result<T, Refusal>,
) -> Result<Vec<T>, Refusal> {
    if r.at() != b'[' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut out = Vec::new();
    r.skip_ws();
    if r.at() != b']' {
        loop {
            r.skip_ws();
            out.push(elem(r)?);
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b']' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    Ok(out)
}

fn digits(s: &[u8], i: usize, n: usize) -> bool {
    s.len() >= i + n && s[i..i + n].iter().all(|c| c.is_ascii_digit())
}

fn date_part(s: &[u8]) -> bool {
    s.len() >= 19
        && digits(s, 0, 4) && s[4] == b'-' && digits(s, 5, 2) && s[7] == b'-' && digits(s, 8, 2)
        && digits(s, 11, 2) && s[13] == b':' && digits(s, 14, 2) && s[16] == b':' && digits(s, 17, 2)
}

/// [DEF-G1] rfc3339-wide: what a reader accepts. Any fraction of one to nine
/// digits or none, either case of the separators, and a numeric offset.
fn lexical_timestamp(text: &str) -> bool {
    let s = text.as_bytes();
    if !date_part(s) || (s[10] != b'T' && s[10] != b't') {
        return false;
    }
    let mut i = 19;
    if i < s.len() && s[i] == b'.' {
        i += 1;
        let start = i;
        while i < s.len() && s[i].is_ascii_digit() {
            i += 1;
        }
        if i - start < 1 || i - start > 9 {
            return false;
        }
    }
    if i >= s.len() {
        return false;
    }
    if s[i] == b'Z' || s[i] == b'z' {
        return i + 1 == s.len();
    }
    if s[i] != b'+' && s[i] != b'-' {
        return false;
    }
    s.len() == i + 6 && digits(s, i + 1, 2) && s[i + 3] == b':' && digits(s, i + 4, 2)
}

/// [DEF-G2] rfc3339-micros: what a writer emits. Exactly six fractional digits,
/// upper-case separators, UTC.
pub fn micros_timestamp(text: &str) -> bool {
    text.len() == 27 && normalized_timestamp(text) == text
}

fn read_timestamp(r: &mut Reader) -> Result<String, Refusal> {
    let at = r.pos;
    let s = r.string()?;
    if !wide_timestamp(&s) {
        r.pos = at;
        return r.refuse("bad_timestamp");
    }
    Ok(s)
}

fn timestamp_number(s: &[u8], at: usize, n: usize) -> i32 {
    s[at..at+n].iter().fold(0, |v,c| v*10+i32::from(c-b'0'))
}
fn timestamp_days(y: i32, m: i32) -> i32 {
    if m==2 {return if y%4==0 && (y%100!=0 || y%400==0) {29} else {28};}
    if m==4 || m==6 || m==9 || m==11 {30} else {31}
}
fn normalized_timestamp(text: &str) -> String {
    if !lexical_timestamp(text) {return String::new();}
    let s=text.as_bytes();
    let (mut y,mut m,mut d)=(timestamp_number(s,0,4),timestamp_number(s,5,2),timestamp_number(s,8,2));
    let (h,minute,sec)=(timestamp_number(s,11,2),timestamp_number(s,14,2),timestamp_number(s,17,2));
    if m<1 || m>12 || d<1 || d>timestamp_days(y,m) || h>23 || minute>59 || sec>59 {return String::new();}
    let mut i=19; let mut fraction=&s[0..0];
    if s[i]==b'.' {i+=1; let start=i; while s[i].is_ascii_digit() {i+=1;} fraction=&s[start..i];}
    let mut total=h*60+minute;
    if s[i]==b'+' || s[i]==b'-' {
        let (oh,om)=(timestamp_number(s,i+1,2),timestamp_number(s,i+4,2));
        if oh>23 || om>59 {return String::new();}
        total += (if s[i]==b'+' {-1} else {1})*(oh*60+om);
    }
    if total<0 {total+=1440; d-=1;} else if total>=1440 {total-=1440; d+=1;}
    if d==0 {m-=1; if m==0 {y-=1; m=12;} d=timestamp_days(y,m);}
    if d>timestamp_days(y,m) {d=1; m+=1; if m==13 {y+=1; m=1;}}
    if !(0..=9999).contains(&y) {return String::new();}
    let mut out=*b"0000-00-00T00:00:00.000000Z";
    let mut put=|at: usize,width: usize,mut value: i32| {for k in (0..width).rev() {out[at+k]=b'0'+(value%10) as u8; value/=10;}};
    put(0,4,y); put(5,2,m); put(8,2,d); put(11,2,total/60); put(14,2,total%60); put(17,2,sec);
    for k in 0..fraction.len().min(6) {out[20+k]=fraction[k];}
    String::from_utf8(out.to_vec()).unwrap()
}
pub fn wide_timestamp(text: &str) -> bool {!normalized_timestamp(text).is_empty()}
fn write_timestamp(text: &str) -> String {
    let result=normalized_timestamp(text);
    assert!(!result.is_empty(), "bad_timestamp");
    result
}

fn decode_hostallowance(r: &mut Reader) -> Result<HostAllowance, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = HostAllowance::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "hosts" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.hosts = r.str_list()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1 != 1 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_pickrequest(r: &mut Reader) -> Result<PickRequest, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = PickRequest::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "model" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.model = r.string()?;
                }
                "fresh" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.fresh = r.boolean()?;
                }
                "allowed" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    v.allowed = Some(decode_hostallowance(r)?);
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 3 != 3 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_caller(r: &mut Reader) -> Result<Caller, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = Caller::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "user_description" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.user_description = r.string()?;
                }
                "path_description" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.path_description = r.string()?;
                }
                _ => {
                    r.skip_value()?;
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 3 != 3 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_observation(r: &mut Reader) -> Result<Observation, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = Observation::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "caller" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.caller = decode_caller(r)?;
                }
                "took_ms" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.took_ms = r.integer(i64::MIN, i64::MAX)?;
                }
                "cache_age_ms" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    v.cache_age_ms = r.integer(i64::MIN, i64::MAX)?;
                }
                _ => {
                    r.skip_value()?;
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 7 != 7 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_alias(r: &mut Reader) -> Result<Alias, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = Alias::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "host" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.host = r.string()?;
                }
                "name" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.name = r.string()?;
                }
                "resident" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    v.resident = r.boolean()?;
                }
                "servable" => {
                    if seen & 8 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 8;
                    v.servable = r.boolean()?;
                }
                _ => {
                    r.skip_value()?;
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 15 != 15 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_family(r: &mut Reader) -> Result<Family, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = Family::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "family" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.family = r.string()?;
                }
                "names" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.names = decode_list(r, decode_alias)?;
                }
                _ => {
                    r.skip_value()?;
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 3 != 3 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_modelssnapshot(r: &mut Reader) -> Result<ModelsSnapshot, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = ModelsSnapshot::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "observation" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.observation = decode_observation(r)?;
                }
                "models" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.models = decode_list(r, decode_family)?;
                }
                _ => {
                    r.skip_value()?;
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 3 != 3 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_hoststate(r: &mut Reader) -> Result<HostState, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = HostState::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "host" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.host = r.string()?;
                }
                "base" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.base = r.string()?;
                }
                "up" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    v.up = r.boolean()?;
                }
                "why" => {
                    if seen & 8 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 8;
                    v.why = r.string()?;
                }
                "installed" => {
                    if seen & 16 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 16;
                    v.installed = r.integer(i64::MIN, i64::MAX)?;
                }
                "resident" => {
                    if seen & 32 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 32;
                    v.resident = r.str_list()?;
                }
                "servable" => {
                    if seen & 64 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 64;
                    v.servable = r.boolean()?;
                }
                _ => {
                    r.skip_value()?;
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 127 != 127 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_ask(r: &mut Reader) -> Result<Ask, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = Ask::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "at" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.at = read_timestamp(r)?;
                }
                "caller" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.caller = r.string()?;
                }
                "user" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    v.user = r.string()?;
                }
                "model" => {
                    if seen & 8 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 8;
                    v.model = r.string()?;
                }
                "family" => {
                    if seen & 16 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 16;
                    v.family = r.string()?;
                }
                "verdict" => {
                    if seen & 32 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 32;
                    v.verdict = r.string()?;
                }
                "host" => {
                    if seen & 64 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 64;
                    v.host = r.string()?;
                }
                _ => {
                    r.skip_value()?;
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 127 != 127 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_hostssnapshot(r: &mut Reader) -> Result<HostsSnapshot, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = HostsSnapshot::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "observation" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.observation = decode_observation(r)?;
                }
                "hosts" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.hosts = decode_list(r, decode_hoststate)?;
                }
                "doubled" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    v.doubled = r.str_list()?;
                }
                "asked" => {
                    if seen & 8 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 8;
                    v.asked = decode_list(r, decode_ask)?;
                }
                _ => {
                    r.skip_value()?;
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 15 != 15 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_decision(r: &mut Reader) -> Result<Decision, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = Decision::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "asked" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.asked = r.string()?;
                }
                "family" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.family = r.string()?;
                }
                "verdict" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    v.verdict = r.string()?;
                }
                "host" => {
                    if seen & 8 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 8;
                    v.host = r.string()?;
                }
                "model" => {
                    if seen & 16 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 16;
                    v.model = r.string()?;
                }
                "endpoint" => {
                    if seen & 32 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 32;
                    v.endpoint = r.string()?;
                }
                "installed_on" => {
                    if seen & 64 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 64;
                    v.installed_on = r.str_list()?;
                }
                "authorised" => {
                    if seen & 128 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 128;
                    v.authorised = Some(decode_hostallowance(r)?);
                }
                "withheld" => {
                    if seen & 256 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 256;
                    v.withheld = r.str_list()?;
                }
                "loads" => {
                    if seen & 512 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 512;
                    v.loads = r.integer(i64::MIN, i64::MAX)?;
                }
                "why" => {
                    if seen & 1024 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1024;
                    v.why = r.string()?;
                }
                _ => {
                    r.skip_value()?;
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1919 != 1919 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_pickresult(r: &mut Reader) -> Result<PickResult, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = PickResult::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "observation" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.observation = decode_observation(r)?;
                }
                "decision" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.decision = decode_decision(r)?;
                }
                _ => {
                    r.skip_value()?;
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 3 != 3 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oaroutermodelsarguments(r: &mut Reader) -> Result<OARouterModelsArguments, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OARouterModelsArguments::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "fresh" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.fresh = r.boolean()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1 != 1 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oarouterhostsarguments(r: &mut Reader) -> Result<OARouterHostsArguments, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OARouterHostsArguments::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "fresh" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.fresh = r.boolean()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1 != 1 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oarouterpickarguments(r: &mut Reader) -> Result<OARouterPickArguments, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OARouterPickArguments::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "request" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.request = decode_pickrequest(r)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1 != 1 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oaserviceframe(r: &mut Reader) -> Result<OAServiceFrame, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAServiceFrame::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "version" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.version = r.integer(-2147483648, 2147483647)? as i32;
                }
                "service" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.service = r.string()?;
                }
                "method" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    v.method = r.string()?;
                }
                "arguments" => {
                    if seen & 8 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 8;
                    v.arguments = r.raw_value()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 15 != 15 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oaservicereply(r: &mut Reader) -> Result<OAServiceReply, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAServiceReply::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "version" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.version = r.integer(-2147483648, 2147483647)? as i32;
                }
                "service" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.service = r.string()?;
                }
                "method" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    v.method = r.string()?;
                }
                "ok" => {
                    if seen & 8 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 8;
                    v.ok = r.boolean()?;
                }
                "payload" => {
                    if seen & 16 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 16;
                    v.payload = r.raw_value()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 31 != 31 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oaserviceerror(r: &mut Reader) -> Result<OAServiceError, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAServiceError::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "code" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.code = r.string()?;
                }
                "message" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.message = r.string()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 3 != 3 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oaroutermodelsresult(r: &mut Reader) -> Result<OARouterModelsResult, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OARouterModelsResult::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "value" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.value = decode_modelssnapshot(r)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1 != 1 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oarouterhostsresult(r: &mut Reader) -> Result<OARouterHostsResult, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OARouterHostsResult::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "value" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.value = decode_hostssnapshot(r)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1 != 1 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oarouterpickresult(r: &mut Reader) -> Result<OARouterPickResult, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OARouterPickResult::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "value" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.value = decode_pickresult(r)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1 != 1 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

pub fn decode(data: &[u8]) -> Result<PickRequest, Refusal> {
    let mut r = Reader { buf: data, pos: 0, depth: 0 };
    r.skip_ws();
    let v = decode_pickrequest(&mut r)?;
    r.skip_ws();
    if r.pos < r.buf.len() {
        return r.refuse("trailing_bytes");
    }
    Ok(v)
}

// REFUSALS is in the order two of them are chosen between.
pub const REFUSALS: [&str; 11] = ["malformed", "bad_string", "number_spelling", "wrong_type", "bad_timestamp", "depth_exceeded", "duplicate_key", "duplicate_field", "unknown_field", "missing_field", "trailing_bytes"];

pub fn refusal_rank(word: &str) -> i32 {
    match REFUSALS.iter().position(|w| *w == word) {
        Some(i) => i as i32,
        None => -1,
    }
}

#[allow(unused_variables)]
fn service_check_hostallowance(v: &HostAllowance) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_pickrequest(v: &PickRequest) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    if let Some(value) = &v.allowed { service_check_hostallowance(value)?; }
    Ok(())
}

#[allow(unused_variables)]
fn service_check_caller(v: &Caller) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_observation(v: &Observation) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    service_check_caller(&v.caller)?;
    Ok(())
}

#[allow(unused_variables)]
fn service_check_alias(v: &Alias) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_family(v: &Family) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    for value in &v.names { service_check_alias(value)?; }
    Ok(())
}

#[allow(unused_variables)]
fn service_check_modelssnapshot(v: &ModelsSnapshot) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    service_check_observation(&v.observation)?;
    for value in &v.models { service_check_family(value)?; }
    Ok(())
}

#[allow(unused_variables)]
fn service_check_hoststate(v: &HostState) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_ask(v: &Ask) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_hostssnapshot(v: &HostsSnapshot) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    service_check_observation(&v.observation)?;
    for value in &v.hosts { service_check_hoststate(value)?; }
    for value in &v.asked { service_check_ask(value)?; }
    Ok(())
}

#[allow(unused_variables)]
fn service_check_decision(v: &Decision) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    if let Some(value) = &v.authorised { service_check_hostallowance(value)?; }
    Ok(())
}

#[allow(unused_variables)]
fn service_check_pickresult(v: &PickResult) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    service_check_observation(&v.observation)?;
    service_check_decision(&v.decision)?;
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oaroutermodelsarguments(v: &OARouterModelsArguments) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oarouterhostsarguments(v: &OARouterHostsArguments) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oarouterpickarguments(v: &OARouterPickArguments) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    service_check_pickrequest(&v.request)?;
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oaserviceframe(v: &OAServiceFrame) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oaservicereply(v: &OAServiceReply) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oaserviceerror(v: &OAServiceError) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oaroutermodelsresult(v: &OARouterModelsResult) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    service_check_modelssnapshot(&v.value)?;
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oarouterhostsresult(v: &OARouterHostsResult) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    service_check_hostssnapshot(&v.value)?;
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oarouterpickresult(v: &OARouterPickResult) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    service_check_pickresult(&v.value)?;
    Ok(())
}

/// Common generated framing boundary; implementation owns waiting and identity.
pub use abstraction_frame::FrameTransport;

#[derive(Debug)]
pub struct ServiceError { pub code: String, pub message: String }
#[derive(Debug)]
pub enum CallError<E> {
    /// Transport failure does not establish whether the receiver accepted work.
    Transport(E),
    Refusal(Refusal),
    Dispatch(&'static str),
    Service(ServiceError),
}
fn service_decode<T>(data: &[u8], decode: fn(&mut Reader) -> Result<T, Refusal>) -> Result<T, Refusal> {
    let mut r = Reader { buf: data, pos: 0, depth: 0 };
    r.skip_ws();
    let value = decode(&mut r)?;
    r.skip_ws();
    if r.pos != data.len() { return r.refuse("trailing_bytes"); }
    Ok(value)
}
fn service_encode<T>(value: &T, check: fn(&T) -> Result<(), Refusal>, encode: fn(&mut Vec<u8>, &T, i32), decode: fn(&mut Reader) -> Result<T, Refusal>) -> Result<Vec<u8>, Refusal> {
    check(value)?;
    let mut data = Vec::new();
    encode(&mut data, value, 0);
    service_decode(&data, decode)?;
    Ok(data)
}

#[allow(non_snake_case)]
pub trait Router {
    type Error;
    fn Models(&self, arg0: bool) -> Result<ModelsSnapshot, Self::Error>;
    fn Hosts(&self, arg0: bool) -> Result<HostsSnapshot, Self::Error>;
    fn Pick(&self, arg0: PickRequest) -> Result<PickResult, Self::Error>;
}

pub struct RouterClient<T> { transport: T }
impl<T> RouterClient<T> {
    pub fn new(transport: T) -> Self { Self { transport } }
    pub fn transport(&self) -> &T { &self.transport }
}
#[allow(non_snake_case)]
impl<T: FrameTransport> Router for RouterClient<T> {
    type Error = CallError<T::Error>;
    fn Models(&self, arg0: bool) -> Result<ModelsSnapshot, Self::Error> {
        let args = OARouterModelsArguments { fresh: arg0, };
        let arguments = service_encode(&args, service_check_oaroutermodelsarguments, enc_oaroutermodelsarguments, decode_oaroutermodelsarguments).map_err(CallError::Refusal)?;
        let request = OAServiceFrame { version: 1, service: "abstraction.router/router@1".into(), method: "Models".into(), arguments };
        let frame = service_encode(&request, service_check_oaserviceframe, enc_oaserviceframe, decode_oaserviceframe).map_err(CallError::Refusal)?;
        let reply = self.transport.exchange_frame(&frame).map_err(CallError::Transport)?;
        let reply = service_decode(&reply, decode_oaservicereply).map_err(CallError::Refusal)?;
        if reply.version != 1 { return Err(CallError::Dispatch("unknown_version")); }
        if reply.service != "abstraction.router/router@1" || reply.method != "Models" { return Err(CallError::Dispatch("mismatched_response")); }
        if !reply.ok {
            let error = service_decode(&reply.payload, decode_oaserviceerror).map_err(CallError::Refusal)?;
            if error.code.is_empty() { return Err(CallError::Dispatch("invalid_error")); }
            return Err(CallError::Service(ServiceError { code: error.code, message: error.message }));
        }
        let result = service_decode(&reply.payload, decode_oaroutermodelsresult).map_err(CallError::Refusal)?;
        Ok(result.value)
    }
    fn Hosts(&self, arg0: bool) -> Result<HostsSnapshot, Self::Error> {
        let args = OARouterHostsArguments { fresh: arg0, };
        let arguments = service_encode(&args, service_check_oarouterhostsarguments, enc_oarouterhostsarguments, decode_oarouterhostsarguments).map_err(CallError::Refusal)?;
        let request = OAServiceFrame { version: 1, service: "abstraction.router/router@1".into(), method: "Hosts".into(), arguments };
        let frame = service_encode(&request, service_check_oaserviceframe, enc_oaserviceframe, decode_oaserviceframe).map_err(CallError::Refusal)?;
        let reply = self.transport.exchange_frame(&frame).map_err(CallError::Transport)?;
        let reply = service_decode(&reply, decode_oaservicereply).map_err(CallError::Refusal)?;
        if reply.version != 1 { return Err(CallError::Dispatch("unknown_version")); }
        if reply.service != "abstraction.router/router@1" || reply.method != "Hosts" { return Err(CallError::Dispatch("mismatched_response")); }
        if !reply.ok {
            let error = service_decode(&reply.payload, decode_oaserviceerror).map_err(CallError::Refusal)?;
            if error.code.is_empty() { return Err(CallError::Dispatch("invalid_error")); }
            return Err(CallError::Service(ServiceError { code: error.code, message: error.message }));
        }
        let result = service_decode(&reply.payload, decode_oarouterhostsresult).map_err(CallError::Refusal)?;
        Ok(result.value)
    }
    fn Pick(&self, arg0: PickRequest) -> Result<PickResult, Self::Error> {
        let args = OARouterPickArguments { request: arg0, };
        let arguments = service_encode(&args, service_check_oarouterpickarguments, enc_oarouterpickarguments, decode_oarouterpickarguments).map_err(CallError::Refusal)?;
        let request = OAServiceFrame { version: 1, service: "abstraction.router/router@1".into(), method: "Pick".into(), arguments };
        let frame = service_encode(&request, service_check_oaserviceframe, enc_oaserviceframe, decode_oaserviceframe).map_err(CallError::Refusal)?;
        let reply = self.transport.exchange_frame(&frame).map_err(CallError::Transport)?;
        let reply = service_decode(&reply, decode_oaservicereply).map_err(CallError::Refusal)?;
        if reply.version != 1 { return Err(CallError::Dispatch("unknown_version")); }
        if reply.service != "abstraction.router/router@1" || reply.method != "Pick" { return Err(CallError::Dispatch("mismatched_response")); }
        if !reply.ok {
            let error = service_decode(&reply.payload, decode_oaserviceerror).map_err(CallError::Refusal)?;
            if error.code.is_empty() { return Err(CallError::Dispatch("invalid_error")); }
            return Err(CallError::Service(ServiceError { code: error.code, message: error.message }));
        }
        let result = service_decode(&reply.payload, decode_oarouterpickresult).map_err(CallError::Refusal)?;
        Ok(result.value)
    }
}
