// Code generated by abstraction-idl from abstraction-router/router.thrift. DO NOT EDIT.

#pragma once

#include <cstddef>
#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <string_view>
#include <vector>

namespace abstraction::router {

using Raw = std::string;

inline void esc(std::string& out, const std::string& s);

inline void esc_byte(std::string& out, unsigned char c) {
    static const char* kHex = "0123456789abcdef";
    switch (c) {
        case '"': out += "\\\""; return;
        case '\\': out += "\\\\"; return;
        case 0x08: out += "\\b"; return;
        case 0x0c: out += "\\f"; return;
        case '\n': out += "\\n"; return;
        case '\r': out += "\\r"; return;
        case '\t': out += "\\t"; return;
        default: break;
    }
    if (c < 0x20) {
        out += "\\u00";
        out += kHex[c >> 4];
        out += kHex[c & 0x0F];
    } else {
        out += static_cast<char>(c);
    }
}

inline void num(std::string& out, std::int64_t n) { out += std::to_string(n); }

inline void pad(std::string& out, int depth) {
    out.append(static_cast<std::size_t>(depth) * 2, ' ');
}

inline void strs(std::string& out, const std::vector<std::string>& v, int depth) {
    if (v.empty()) { out += "[]"; return; }
    out += "[\n";
    for (std::size_t i = 0; i < v.size(); ++i) {
        pad(out, depth + 1);
        esc(out, v[i]);
        if (i + 1 < v.size()) out += ',';
        out += '\n';
    }
    pad(out, depth);
    out += ']';
}

inline bool ws(unsigned char c) { return c == ' ' || c == '\t' || c == '\n' || c == '\r'; }

inline void raw(std::string& out, const std::string& s, int depth) {
    const std::size_t n = s.size();
    for (std::size_t i = 0; i < n;) {
        const unsigned char c = static_cast<unsigned char>(s[i]);
        if (ws(c)) {
            ++i;
        } else if (c == '"') {
            std::size_t j = i + 1;
            while (j < n) {
                if (s[j] == '\\') { j += 2; continue; }
                if (s[j] == '"') { ++j; break; }
                ++j;
            }
            out.append(s, i, j - i);
            i = j;
        } else if (c == '{' || c == '[') {
            out += static_cast<char>(c);
            ++i;
            std::size_t j = i;
            while (j < n && ws(static_cast<unsigned char>(s[j]))) ++j;
            if (j < n && (s[j] == '}' || s[j] == ']')) {
                out += s[j];
                i = j + 1;
            } else {
                ++depth;
                out += '\n';
                pad(out, depth);
            }
        } else if (c == '}' || c == ']') {
            --depth;
            out += '\n';
            pad(out, depth);
            out += static_cast<char>(c);
            ++i;
        } else if (c == ',') {
            out += ",\n";
            pad(out, depth);
            ++i;
        } else if (c == ':') {
            out += ": ";
            ++i;
        } else {
            out += static_cast<char>(c);
            ++i;
        }
    }
}

// std::char_traits<char>::compare is specified to order by unsigned char, so a
// std::map<std::string, ...> already walks its keys in UTF-8 byte order — which
// is what the definition declares. Nothing sorts here because nothing needs to.
inline void rawmap(std::string& out, const std::map<std::string, Raw>& m, int depth) {
    if (m.empty()) { out += "{}"; return; }
    out += "{\n";
    std::size_t i = 0;
    for (const auto& kv : m) {
        pad(out, depth + 1);
        esc(out, kv.first);
        out += ": ";
        raw(out, kv.second, depth + 1);
        if (++i < m.size()) out += ',';
        out += '\n';
    }
    pad(out, depth);
    out += '}';
}

inline void esc(std::string& out, const std::string& s) {
    out += '"';
    for (unsigned char c : s) esc_byte(out, c);
    out += '"';
}

inline bool wide_timestamp(std::string_view);
inline std::string normalized_timestamp(std::string_view);
inline std::string write_timestamp(std::string_view);

template <typename T>
inline void enc_list(std::string& out, const std::vector<T>& v, int depth,
                     void (*enc)(std::string&, const T&, int)) {
    if (v.empty()) { out += "[]"; return; }
    out += "[\n";
    for (std::size_t i = 0; i < v.size(); ++i) {
        pad(out, depth + 1);
        enc(out, v[i], depth + 1);
        if (i + 1 < v.size()) out += ',';
        out += '\n';
    }
    pad(out, depth);
    out += ']';
}

inline const std::vector<std::string> kVerdicts = {"resident", "would-load", "unservable", "not-here", "unparseable", "unauthorised"};

struct HostAllowance {
    std::vector<std::string> hosts;
};

struct PickRequest {
    std::string model;
    bool fresh = false;
    std::optional<HostAllowance> allowed;
};

struct Caller {
    std::string user_description;
    std::string path_description;
};

struct Observation {
    Caller caller;
    std::int64_t took_ms = 0;
    std::int64_t cache_age_ms = 0;
};

struct Alias {
    std::string host;
    std::string name;
    bool resident = false;
    bool servable = false;
};

struct Family {
    std::string family;
    std::vector<Alias> names;
};

struct ModelsSnapshot {
    Observation observation;
    std::vector<Family> models;
};

struct HostState {
    std::string host;
    std::string base;
    bool up = false;
    std::string why;
    std::int64_t installed = 0;
    std::vector<std::string> resident;
    bool servable = false;
};

struct Ask {
    std::string at;
    std::string caller;
    std::string user;
    std::string model;
    std::string family;
    std::string verdict;
    std::string host;
};

struct HostsSnapshot {
    Observation observation;
    std::vector<HostState> hosts;
    std::vector<std::string> doubled;
    std::vector<Ask> asked;
};

struct Decision {
    std::string asked;
    std::string family;
    std::string verdict;
    std::string host;
    std::string model;
    std::string endpoint;
    std::vector<std::string> installed_on;
    std::optional<HostAllowance> authorised;
    std::vector<std::string> withheld;
    std::int64_t loads = 0;
    std::string why;
};

struct PickResult {
    Observation observation;
    Decision decision;
};

struct OARouterModelsArguments {
    bool fresh = false;
};

struct OARouterHostsArguments {
    bool fresh = false;
};

struct OARouterPickArguments {
    PickRequest request;
};

struct OAServiceFrame {
    std::int32_t version = 0;
    std::string service;
    std::string method;
    Raw arguments;
};

struct OAServiceReply {
    std::int32_t version = 0;
    std::string service;
    std::string method;
    bool ok = false;
    Raw payload;
};

struct OAServiceError {
    std::string code;
    std::string message;
};

struct OARouterModelsResult {
    ModelsSnapshot value;
};

struct OARouterHostsResult {
    HostsSnapshot value;
};

struct OARouterPickResult {
    PickResult value;
};

inline void enc_hostallowance(std::string& out, const HostAllowance& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "hosts");
    out += ": ";
    strs(out, v.hosts, depth + 1);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_pickrequest(std::string& out, const PickRequest& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "model");
    out += ": ";
    esc(out, v.model);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "fresh");
    out += ": ";
    out += v.fresh ? "true" : "false";
    if (v.allowed.has_value()) {
        out += ',';
        out += '\n';
        pad(out, depth + 1);
        esc(out, "allowed");
        out += ": ";
        enc_hostallowance(out, *v.allowed, depth + 1);
    }
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_caller(std::string& out, const Caller& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "user_description");
    out += ": ";
    esc(out, v.user_description);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "path_description");
    out += ": ";
    esc(out, v.path_description);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_observation(std::string& out, const Observation& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "caller");
    out += ": ";
    enc_caller(out, v.caller, depth + 1);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "took_ms");
    out += ": ";
    num(out, v.took_ms);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "cache_age_ms");
    out += ": ";
    num(out, v.cache_age_ms);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_alias(std::string& out, const Alias& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "host");
    out += ": ";
    esc(out, v.host);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "name");
    out += ": ";
    esc(out, v.name);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "resident");
    out += ": ";
    out += v.resident ? "true" : "false";
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "servable");
    out += ": ";
    out += v.servable ? "true" : "false";
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_family(std::string& out, const Family& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "family");
    out += ": ";
    esc(out, v.family);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "names");
    out += ": ";
    enc_list<Alias>(out, v.names, depth + 1, enc_alias);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_modelssnapshot(std::string& out, const ModelsSnapshot& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "observation");
    out += ": ";
    enc_observation(out, v.observation, depth + 1);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "models");
    out += ": ";
    enc_list<Family>(out, v.models, depth + 1, enc_family);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_hoststate(std::string& out, const HostState& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "host");
    out += ": ";
    esc(out, v.host);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "base");
    out += ": ";
    esc(out, v.base);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "up");
    out += ": ";
    out += v.up ? "true" : "false";
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "why");
    out += ": ";
    esc(out, v.why);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "installed");
    out += ": ";
    num(out, v.installed);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "resident");
    out += ": ";
    strs(out, v.resident, depth + 1);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "servable");
    out += ": ";
    out += v.servable ? "true" : "false";
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_ask(std::string& out, const Ask& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "at");
    out += ": ";
    esc(out, write_timestamp(v.at));
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "caller");
    out += ": ";
    esc(out, v.caller);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "user");
    out += ": ";
    esc(out, v.user);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "model");
    out += ": ";
    esc(out, v.model);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "family");
    out += ": ";
    esc(out, v.family);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "verdict");
    out += ": ";
    esc(out, v.verdict);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "host");
    out += ": ";
    esc(out, v.host);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_hostssnapshot(std::string& out, const HostsSnapshot& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "observation");
    out += ": ";
    enc_observation(out, v.observation, depth + 1);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "hosts");
    out += ": ";
    enc_list<HostState>(out, v.hosts, depth + 1, enc_hoststate);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "doubled");
    out += ": ";
    strs(out, v.doubled, depth + 1);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "asked");
    out += ": ";
    enc_list<Ask>(out, v.asked, depth + 1, enc_ask);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_decision(std::string& out, const Decision& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "asked");
    out += ": ";
    esc(out, v.asked);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "family");
    out += ": ";
    esc(out, v.family);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "verdict");
    out += ": ";
    esc(out, v.verdict);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "host");
    out += ": ";
    esc(out, v.host);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "model");
    out += ": ";
    esc(out, v.model);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "endpoint");
    out += ": ";
    esc(out, v.endpoint);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "installed_on");
    out += ": ";
    strs(out, v.installed_on, depth + 1);
    if (v.authorised.has_value()) {
        out += ',';
        out += '\n';
        pad(out, depth + 1);
        esc(out, "authorised");
        out += ": ";
        enc_hostallowance(out, *v.authorised, depth + 1);
    }
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "withheld");
    out += ": ";
    strs(out, v.withheld, depth + 1);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "loads");
    out += ": ";
    num(out, v.loads);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "why");
    out += ": ";
    esc(out, v.why);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_pickresult(std::string& out, const PickResult& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "observation");
    out += ": ";
    enc_observation(out, v.observation, depth + 1);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "decision");
    out += ": ";
    enc_decision(out, v.decision, depth + 1);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oaroutermodelsarguments(std::string& out, const OARouterModelsArguments& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "fresh");
    out += ": ";
    out += v.fresh ? "true" : "false";
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oarouterhostsarguments(std::string& out, const OARouterHostsArguments& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "fresh");
    out += ": ";
    out += v.fresh ? "true" : "false";
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oarouterpickarguments(std::string& out, const OARouterPickArguments& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "request");
    out += ": ";
    enc_pickrequest(out, v.request, depth + 1);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oaserviceframe(std::string& out, const OAServiceFrame& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "version");
    out += ": ";
    num(out, v.version);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "service");
    out += ": ";
    esc(out, v.service);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "method");
    out += ": ";
    esc(out, v.method);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "arguments");
    out += ": ";
    out += v.arguments;
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oaservicereply(std::string& out, const OAServiceReply& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "version");
    out += ": ";
    num(out, v.version);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "service");
    out += ": ";
    esc(out, v.service);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "method");
    out += ": ";
    esc(out, v.method);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "ok");
    out += ": ";
    out += v.ok ? "true" : "false";
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "payload");
    out += ": ";
    out += v.payload;
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oaserviceerror(std::string& out, const OAServiceError& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "code");
    out += ": ";
    esc(out, v.code);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "message");
    out += ": ";
    esc(out, v.message);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oaroutermodelsresult(std::string& out, const OARouterModelsResult& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "value");
    out += ": ";
    enc_modelssnapshot(out, v.value, depth + 1);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oarouterhostsresult(std::string& out, const OARouterHostsResult& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "value");
    out += ": ";
    enc_hostssnapshot(out, v.value, depth + 1);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oarouterpickresult(std::string& out, const OARouterPickResult& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "value");
    out += ": ";
    enc_pickresult(out, v.value, depth + 1);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline std::string encode(const PickRequest& v) {
    std::string out;
    enc_pickrequest(out, v, 0);
    out += '\n';
    return out;
}

inline constexpr int kDepthLimit = 64;
inline constexpr std::size_t kI64Digits = 19;

class Refusal : public std::runtime_error {
public:
    Refusal(const char* word, std::size_t offset)
        : std::runtime_error(std::string("refused: ") + word + " at byte " + std::to_string(offset)),
          word(word),
          offset(offset) {}
    const char* word;
    std::size_t offset;
};

inline void append_rune(std::string& out, std::uint32_t cp) {
    if (cp < 0x80) {
        out += static_cast<char>(cp);
    } else if (cp < 0x800) {
        out += static_cast<char>(0xC0 | (cp >> 6));
        out += static_cast<char>(0x80 | (cp & 0x3F));
    } else if (cp < 0x10000) {
        out += static_cast<char>(0xE0 | (cp >> 12));
        out += static_cast<char>(0x80 | ((cp >> 6) & 0x3F));
        out += static_cast<char>(0x80 | (cp & 0x3F));
    } else {
        out += static_cast<char>(0xF0 | (cp >> 18));
        out += static_cast<char>(0x80 | ((cp >> 12) & 0x3F));
        out += static_cast<char>(0x80 | ((cp >> 6) & 0x3F));
        out += static_cast<char>(0x80 | (cp & 0x3F));
    }
}

inline bool valid_utf8(const std::string& b) {
    for (std::size_t i = 0; i < b.size();) {
        const unsigned char c = static_cast<unsigned char>(b[i]);
        if (c < 0x80) { ++i; continue; }
        std::size_t n = 0;
        std::uint32_t cp = 0;
        if ((c >> 5) == 0x6) { n = 2; cp = c & 0x1Fu; }
        else if ((c >> 4) == 0xE) { n = 3; cp = c & 0x0Fu; }
        else if ((c >> 3) == 0x1E) { n = 4; cp = c & 0x07u; }
        else return false;
        if (i + n > b.size()) return false;
        for (std::size_t k = 1; k < n; ++k) {
            const unsigned char t = static_cast<unsigned char>(b[i + k]);
            if ((t >> 6) != 0x2) return false;
            cp = cp << 6 | (t & 0x3Fu);
        }
        static const std::uint32_t kLowest[5] = {0, 0, 0x80, 0x800, 0x10000};
        if (cp < kLowest[n] || cp > 0x10FFFF || (cp >= 0xD800 && cp <= 0xDFFF)) return false;
        i += n;
    }
    return true;
}

struct Reader {
    std::string_view buf;
    std::size_t pos = 0;
    int depth = 0;

    [[noreturn]] void refuse(const char* word) const { throw Refusal(word, pos); }

    unsigned char at() const {
        return pos < buf.size() ? static_cast<unsigned char>(buf[pos]) : 0;
    }

    bool digit() const { return at() >= '0' && at() <= '9'; }

    void skip_ws() {
        while (pos < buf.size() && ws(static_cast<unsigned char>(buf[pos]))) ++pos;
    }

    void enter() {
        if (++depth > kDepthLimit) refuse("depth_exceeded");
    }

    std::string str() {
        if (at() != '"') refuse("wrong_type");
        ++pos;
        std::string out;
        for (;;) {
            if (pos >= buf.size()) refuse("malformed");
            const unsigned char c = static_cast<unsigned char>(buf[pos]);
            if (c == '"') {
                ++pos;
                if (!valid_utf8(out)) refuse("bad_string");
                return out;
            }
            if (c < 0x20) refuse("bad_string");
            if (c == '\\') {
                escape(out);
            } else {
                out += static_cast<char>(c);
                ++pos;
            }
        }
    }

    void escape(std::string& out) {
        ++pos;
        if (pos >= buf.size()) refuse("malformed");
        const unsigned char c = static_cast<unsigned char>(buf[pos]);
        ++pos;
        switch (c) {
            case '"': case '\\': case '/': out += static_cast<char>(c); return;
            case 'b': out += static_cast<char>(0x08); return;
            case 'f': out += static_cast<char>(0x0c); return;
            case 'n': out += '\n'; return;
            case 'r': out += '\r'; return;
            case 't': out += '\t'; return;
            case 'u': break;
            default: refuse("bad_string");
        }
        std::uint32_t u = hex4();
        if (u >= 0xDC00 && u <= 0xDFFF) refuse("bad_string");
        if (u >= 0xD800 && u <= 0xDBFF) {
            if (pos + 1 >= buf.size() || buf[pos] != '\\' || buf[pos + 1] != 'u') refuse("bad_string");
            pos += 2;
            const std::uint32_t low = hex4();
            if (low < 0xDC00 || low > 0xDFFF) refuse("bad_string");
            u = 0x10000 + ((u - 0xD800) << 10) + (low - 0xDC00);
        }
        append_rune(out, u);
    }

    std::uint32_t hex4() {
        if (pos + 4 > buf.size()) refuse("bad_string");
        std::uint32_t u = 0;
        for (std::size_t i = 0; i < 4; ++i) {
            const unsigned char c = static_cast<unsigned char>(buf[pos + i]);
            if (c >= '0' && c <= '9') u = u << 4 | static_cast<std::uint32_t>(c - '0');
            else if (c >= 'a' && c <= 'f') u = u << 4 | static_cast<std::uint32_t>(c - 'a' + 10);
            else if (c >= 'A' && c <= 'F') u = u << 4 | static_cast<std::uint32_t>(c - 'A' + 10);
            else refuse("bad_string");
        }
        pos += 4;
        return u;
    }

    std::int64_t integer(std::int64_t low, std::int64_t high) {
        const unsigned char c = at();
        if (c != '-' && !digit()) refuse("wrong_type");
        const bool negative = c == '-';
        if (negative) ++pos;
        if (!digit()) refuse("malformed");
        std::uint64_t u = 0;
        if (at() == '0') {
            ++pos;
        } else {
            while (digit()) {
                if (u > 922337203685477580ULL) refuse("number_spelling");
                u = u * 10 + static_cast<std::uint64_t>(at() - '0');
                ++pos;
            }
        }
        const unsigned char after = at();
        if (after == '.' || after == 'e' || after == 'E' || digit()) refuse("number_spelling");
        if (negative && u == 0) refuse("number_spelling");
        std::int64_t n = 0;
        if (negative) {
            if (u > (1ULL << 63)) refuse("number_spelling");
            n = u == (1ULL << 63) ? INT64_MIN : -static_cast<std::int64_t>(u);
        } else {
            if (u > static_cast<std::uint64_t>(INT64_MAX)) refuse("number_spelling");
            n = static_cast<std::int64_t>(u);
        }
        if (n < low || n > high) refuse("number_spelling");
        return n;
    }

    bool boolean() {
        if (at() == 't') { literal("true"); return true; }
        if (at() == 'f') { literal("false"); return false; }
        refuse("wrong_type");
    }

    void literal(std::string_view word) {
        if (buf.substr(pos, word.size()) != word) refuse("malformed");
        pos += word.size();
    }

    std::vector<std::string> str_list() {
        if (at() != '[') refuse("wrong_type");
        enter();
        ++pos;
        std::vector<std::string> out;
        skip_ws();
        if (at() != ']') {
            for (;;) {
                skip_ws();
                out.push_back(str());
                skip_ws();
                if (at() != ',') break;
                ++pos;
            }
        }
        if (at() != ']') refuse("malformed");
        ++pos;
        --depth;
        return out;
    }

    std::map<std::string, Raw> raw_map() {
        if (at() != '{') refuse("wrong_type");
        enter();
        ++pos;
        std::map<std::string, Raw> out;
        skip_ws();
        if (at() != '}') {
            for (;;) {
                skip_ws();
                if (at() != '"') refuse("malformed");
                const std::string k = str();
                if (out.count(k) != 0) refuse("duplicate_key");
                skip_ws();
                if (at() != ':') refuse("malformed");
                ++pos;
                skip_ws();
                out[k] = raw_value();
                skip_ws();
                if (at() != ',') break;
                ++pos;
            }
        }
        if (at() != '}') refuse("malformed");
        ++pos;
        --depth;
        return out;
    }

    Raw raw_value() {
        const std::size_t start = pos;
        skip_value();
        return std::string(buf.substr(start, pos - start));
    }

    void skip_value() {
        const unsigned char c = at();
        if (c == '"') skip_string();
        else if (c == '{' || c == '[') skip_container();
        else if (c == 't') literal("true");
        else if (c == 'f') literal("false");
        else if (c == 'n') literal("null");
        else if (c == '-' || digit()) skip_number();
        else refuse("malformed");
    }

    // An opaque value is validated and carried, never interpreted. Its syntax is
    // the record's own — the same string reader, so an escape, a control byte or
    // a lone surrogate is judged identically at any depth — and what it is free
    // to spell, it keeps: the bytes between these two offsets are what a writer
    // re-emits. A number is walked, never converted, so a value no host type
    // holds survives the reader that carried it.
    void skip_string() { str(); }

    void some_digits() {
        int n = 0;
        while (digit()) { ++pos; ++n; }
        if (n == 0) refuse("number_spelling");
    }

    void skip_number() {
        if (at() == '-') ++pos;
        const unsigned char c = at();
        if (c == '0') ++pos;
        else if (c >= '1' && c <= '9') { while (digit()) ++pos; }
        else refuse("number_spelling");
        if (at() == '.') { ++pos; some_digits(); }
        if (at() == 'e' || at() == 'E') {
            ++pos;
            if (at() == '+' || at() == '-') ++pos;
            some_digits();
        }
    }

    void skip_container() {
        const unsigned char opener = at();
        const char shut = opener == '{' ? '}' : ']';
        enter();
        ++pos;
        skip_ws();
        std::map<std::string, bool> seen;
        if (at() != static_cast<unsigned char>(shut)) {
            for (;;) {
                skip_ws();
                if (opener == '{') {
                    if (at() != '"') refuse("malformed");
                    const std::string k = str();
                    if (!seen.emplace(k, true).second) refuse("duplicate_key");
                    skip_ws();
                    if (at() != ':') refuse("malformed");
                    ++pos;
                    skip_ws();
                }
                skip_value();
                skip_ws();
                if (at() != ',') break;
                ++pos;
            }
        }
        if (at() != static_cast<unsigned char>(shut)) refuse("malformed");
        ++pos;
        --depth;
    }
};

template <typename T>
inline std::vector<T> decode_list(Reader& r, T (*elem)(Reader&)) {
    if (r.at() != '[') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    std::vector<T> out;
    r.skip_ws();
    if (r.at() != ']') {
        for (;;) {
            r.skip_ws();
            out.push_back(elem(r));
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != ']') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    return out;
}

inline bool digits(std::string_view s, std::size_t i, std::size_t n) {
    if (s.size() < i + n) return false;
    for (std::size_t k = 0; k < n; ++k) {
        if (s[i + k] < '0' || s[i + k] > '9') return false;
    }
    return true;
}

inline bool date_part(std::string_view s) {
    return s.size() >= 19 && digits(s, 0, 4) && s[4] == '-' && digits(s, 5, 2) && s[7] == '-' &&
           digits(s, 8, 2) && digits(s, 11, 2) && s[13] == ':' && digits(s, 14, 2) && s[16] == ':' &&
           digits(s, 17, 2);
}

// [DEF-G1] rfc3339-wide: what a reader accepts. Any fraction of one to nine
// digits or none, either case of the separators, and a numeric offset.
inline bool lexical_timestamp(std::string_view s) {
    if (!date_part(s) || (s[10] != 'T' && s[10] != 't')) return false;
    std::size_t i = 19;
    if (i < s.size() && s[i] == '.') {
        ++i;
        const std::size_t start = i;
        while (i < s.size() && s[i] >= '0' && s[i] <= '9') ++i;
        if (i - start < 1 || i - start > 9) return false;
    }
    if (i >= s.size()) return false;
    if (s[i] == 'Z' || s[i] == 'z') return i + 1 == s.size();
    if (s[i] != '+' && s[i] != '-') return false;
    return s.size() == i + 6 && digits(s, i + 1, 2) && s[i + 3] == ':' && digits(s, i + 4, 2);
}

// [DEF-G2] rfc3339-micros: what a writer emits. Exactly six fractional digits,
// upper-case separators, UTC.
inline bool micros_timestamp(std::string_view s) {
    return s.size() == 27 && normalized_timestamp(s) == s;
}

inline std::string read_timestamp(Reader& r) {
    const std::size_t at = r.pos;
    const std::string s = r.str();
    if (!wide_timestamp(s)) {
        r.pos = at;
        r.refuse("bad_timestamp");
    }
    return s;
}

inline int timestamp_number(std::string_view s, std::size_t at, std::size_t n) {
    int v=0; for(std::size_t k=0;k<n;++k) v=v*10+(s[at+k]-'0'); return v;
}
inline int timestamp_days(int y, int m) {
    if(m==2) return y%4==0 && (y%100!=0 || y%400==0) ? 29 : 28;
    return m==4 || m==6 || m==9 || m==11 ? 30 : 31;
}
inline std::string normalized_timestamp(std::string_view s) {
    if(!lexical_timestamp(s)) return {};
    int y=timestamp_number(s,0,4), m=timestamp_number(s,5,2), d=timestamp_number(s,8,2);
    int h=timestamp_number(s,11,2), minute=timestamp_number(s,14,2), sec=timestamp_number(s,17,2);
    if(m<1 || m>12 || d<1 || d>timestamp_days(y,m) || h>23 || minute>59 || sec>59) return {};
    std::size_t i=19; std::string_view fraction;
    if(s[i]=='.') {const auto start=++i; while(s[i]>='0' && s[i]<='9') ++i; fraction=s.substr(start,i-start);}
    int total=h*60+minute;
    if(s[i]=='+' || s[i]=='-') {
        int oh=timestamp_number(s,i+1,2), om=timestamp_number(s,i+4,2);
        if(oh>23 || om>59) return {};
        total += (s[i]=='+' ? -1 : 1)*(oh*60+om);
    }
    if(total<0) {total+=1440; --d;} else if(total>=1440) {total-=1440; ++d;}
    if(d==0) {--m; if(m==0) {--y; m=12;} d=timestamp_days(y,m);}
    if(d>timestamp_days(y,m)) {d=1; ++m; if(m==13) {++y; m=1;}}
    if(y<0 || y>9999) return {};
    std::string out="0000-00-00T00:00:00.000000Z";
    auto put=[&](int at,int width,int value) {for(int k=width-1;k>=0;--k) {out[at+k]=char('0'+value%10); value/=10;}};
    put(0,4,y); put(5,2,m); put(8,2,d); put(11,2,total/60); put(14,2,total%60); put(17,2,sec);
    for(std::size_t k=0;k<6 && k<fraction.size();++k) out[20+k]=fraction[k];
    return out;
}
inline bool wide_timestamp(std::string_view s) {return !normalized_timestamp(s).empty();}
inline std::string write_timestamp(std::string_view s) {
    auto result=normalized_timestamp(s);
    if(result.empty()) throw Refusal("bad_timestamp",0);
    return result;
}

inline HostAllowance decode_hostallowance(Reader& r);
inline PickRequest decode_pickrequest(Reader& r);
inline Caller decode_caller(Reader& r);
inline Observation decode_observation(Reader& r);
inline Alias decode_alias(Reader& r);
inline Family decode_family(Reader& r);
inline ModelsSnapshot decode_modelssnapshot(Reader& r);
inline HostState decode_hoststate(Reader& r);
inline Ask decode_ask(Reader& r);
inline HostsSnapshot decode_hostssnapshot(Reader& r);
inline Decision decode_decision(Reader& r);
inline PickResult decode_pickresult(Reader& r);
inline OARouterModelsArguments decode_oaroutermodelsarguments(Reader& r);
inline OARouterHostsArguments decode_oarouterhostsarguments(Reader& r);
inline OARouterPickArguments decode_oarouterpickarguments(Reader& r);
inline OAServiceFrame decode_oaserviceframe(Reader& r);
inline OAServiceReply decode_oaservicereply(Reader& r);
inline OAServiceError decode_oaserviceerror(Reader& r);
inline OARouterModelsResult decode_oaroutermodelsresult(Reader& r);
inline OARouterHostsResult decode_oarouterhostsresult(Reader& r);
inline OARouterPickResult decode_oarouterpickresult(Reader& r);

inline HostAllowance decode_hostallowance(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    HostAllowance v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "hosts") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.hosts = r.str_list();
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 1u) != 1u) r.refuse("missing_field");
    return v;
}

inline PickRequest decode_pickrequest(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    PickRequest v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "model") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.model = r.str();
            } else if (key == "fresh") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.fresh = r.boolean();
            } else if (key == "allowed") {
                if (seen & 4u) r.refuse("duplicate_field");
                seen |= 4u;
                v.allowed = decode_hostallowance(r);
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 3u) != 3u) r.refuse("missing_field");
    return v;
}

inline Caller decode_caller(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    Caller v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "user_description") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.user_description = r.str();
            } else if (key == "path_description") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.path_description = r.str();
            } else {
                r.skip_value();
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 3u) != 3u) r.refuse("missing_field");
    return v;
}

inline Observation decode_observation(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    Observation v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "caller") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.caller = decode_caller(r);
            } else if (key == "took_ms") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.took_ms = r.integer(INT64_MIN, INT64_MAX);
            } else if (key == "cache_age_ms") {
                if (seen & 4u) r.refuse("duplicate_field");
                seen |= 4u;
                v.cache_age_ms = r.integer(INT64_MIN, INT64_MAX);
            } else {
                r.skip_value();
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 7u) != 7u) r.refuse("missing_field");
    return v;
}

inline Alias decode_alias(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    Alias v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "host") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.host = r.str();
            } else if (key == "name") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.name = r.str();
            } else if (key == "resident") {
                if (seen & 4u) r.refuse("duplicate_field");
                seen |= 4u;
                v.resident = r.boolean();
            } else if (key == "servable") {
                if (seen & 8u) r.refuse("duplicate_field");
                seen |= 8u;
                v.servable = r.boolean();
            } else {
                r.skip_value();
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 15u) != 15u) r.refuse("missing_field");
    return v;
}

inline Family decode_family(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    Family v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "family") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.family = r.str();
            } else if (key == "names") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.names = decode_list<Alias>(r, decode_alias);
            } else {
                r.skip_value();
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 3u) != 3u) r.refuse("missing_field");
    return v;
}

inline ModelsSnapshot decode_modelssnapshot(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    ModelsSnapshot v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "observation") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.observation = decode_observation(r);
            } else if (key == "models") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.models = decode_list<Family>(r, decode_family);
            } else {
                r.skip_value();
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 3u) != 3u) r.refuse("missing_field");
    return v;
}

inline HostState decode_hoststate(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    HostState v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "host") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.host = r.str();
            } else if (key == "base") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.base = r.str();
            } else if (key == "up") {
                if (seen & 4u) r.refuse("duplicate_field");
                seen |= 4u;
                v.up = r.boolean();
            } else if (key == "why") {
                if (seen & 8u) r.refuse("duplicate_field");
                seen |= 8u;
                v.why = r.str();
            } else if (key == "installed") {
                if (seen & 16u) r.refuse("duplicate_field");
                seen |= 16u;
                v.installed = r.integer(INT64_MIN, INT64_MAX);
            } else if (key == "resident") {
                if (seen & 32u) r.refuse("duplicate_field");
                seen |= 32u;
                v.resident = r.str_list();
            } else if (key == "servable") {
                if (seen & 64u) r.refuse("duplicate_field");
                seen |= 64u;
                v.servable = r.boolean();
            } else {
                r.skip_value();
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 127u) != 127u) r.refuse("missing_field");
    return v;
}

inline Ask decode_ask(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    Ask v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "at") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.at = read_timestamp(r);
            } else if (key == "caller") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.caller = r.str();
            } else if (key == "user") {
                if (seen & 4u) r.refuse("duplicate_field");
                seen |= 4u;
                v.user = r.str();
            } else if (key == "model") {
                if (seen & 8u) r.refuse("duplicate_field");
                seen |= 8u;
                v.model = r.str();
            } else if (key == "family") {
                if (seen & 16u) r.refuse("duplicate_field");
                seen |= 16u;
                v.family = r.str();
            } else if (key == "verdict") {
                if (seen & 32u) r.refuse("duplicate_field");
                seen |= 32u;
                v.verdict = r.str();
            } else if (key == "host") {
                if (seen & 64u) r.refuse("duplicate_field");
                seen |= 64u;
                v.host = r.str();
            } else {
                r.skip_value();
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 127u) != 127u) r.refuse("missing_field");
    return v;
}

inline HostsSnapshot decode_hostssnapshot(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    HostsSnapshot v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "observation") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.observation = decode_observation(r);
            } else if (key == "hosts") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.hosts = decode_list<HostState>(r, decode_hoststate);
            } else if (key == "doubled") {
                if (seen & 4u) r.refuse("duplicate_field");
                seen |= 4u;
                v.doubled = r.str_list();
            } else if (key == "asked") {
                if (seen & 8u) r.refuse("duplicate_field");
                seen |= 8u;
                v.asked = decode_list<Ask>(r, decode_ask);
            } else {
                r.skip_value();
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 15u) != 15u) r.refuse("missing_field");
    return v;
}

inline Decision decode_decision(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    Decision v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "asked") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.asked = r.str();
            } else if (key == "family") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.family = r.str();
            } else if (key == "verdict") {
                if (seen & 4u) r.refuse("duplicate_field");
                seen |= 4u;
                v.verdict = r.str();
            } else if (key == "host") {
                if (seen & 8u) r.refuse("duplicate_field");
                seen |= 8u;
                v.host = r.str();
            } else if (key == "model") {
                if (seen & 16u) r.refuse("duplicate_field");
                seen |= 16u;
                v.model = r.str();
            } else if (key == "endpoint") {
                if (seen & 32u) r.refuse("duplicate_field");
                seen |= 32u;
                v.endpoint = r.str();
            } else if (key == "installed_on") {
                if (seen & 64u) r.refuse("duplicate_field");
                seen |= 64u;
                v.installed_on = r.str_list();
            } else if (key == "authorised") {
                if (seen & 128u) r.refuse("duplicate_field");
                seen |= 128u;
                v.authorised = decode_hostallowance(r);
            } else if (key == "withheld") {
                if (seen & 256u) r.refuse("duplicate_field");
                seen |= 256u;
                v.withheld = r.str_list();
            } else if (key == "loads") {
                if (seen & 512u) r.refuse("duplicate_field");
                seen |= 512u;
                v.loads = r.integer(INT64_MIN, INT64_MAX);
            } else if (key == "why") {
                if (seen & 1024u) r.refuse("duplicate_field");
                seen |= 1024u;
                v.why = r.str();
            } else {
                r.skip_value();
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 1919u) != 1919u) r.refuse("missing_field");
    return v;
}

inline PickResult decode_pickresult(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    PickResult v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "observation") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.observation = decode_observation(r);
            } else if (key == "decision") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.decision = decode_decision(r);
            } else {
                r.skip_value();
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 3u) != 3u) r.refuse("missing_field");
    return v;
}

inline OARouterModelsArguments decode_oaroutermodelsarguments(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OARouterModelsArguments v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "fresh") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.fresh = r.boolean();
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 1u) != 1u) r.refuse("missing_field");
    return v;
}

inline OARouterHostsArguments decode_oarouterhostsarguments(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OARouterHostsArguments v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "fresh") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.fresh = r.boolean();
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 1u) != 1u) r.refuse("missing_field");
    return v;
}

inline OARouterPickArguments decode_oarouterpickarguments(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OARouterPickArguments v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "request") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.request = decode_pickrequest(r);
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 1u) != 1u) r.refuse("missing_field");
    return v;
}

inline OAServiceFrame decode_oaserviceframe(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OAServiceFrame v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "version") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.version = static_cast<std::int32_t>(r.integer(INT32_MIN, INT32_MAX));
            } else if (key == "service") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.service = r.str();
            } else if (key == "method") {
                if (seen & 4u) r.refuse("duplicate_field");
                seen |= 4u;
                v.method = r.str();
            } else if (key == "arguments") {
                if (seen & 8u) r.refuse("duplicate_field");
                seen |= 8u;
                v.arguments = r.raw_value();
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 15u) != 15u) r.refuse("missing_field");
    return v;
}

inline OAServiceReply decode_oaservicereply(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OAServiceReply v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "version") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.version = static_cast<std::int32_t>(r.integer(INT32_MIN, INT32_MAX));
            } else if (key == "service") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.service = r.str();
            } else if (key == "method") {
                if (seen & 4u) r.refuse("duplicate_field");
                seen |= 4u;
                v.method = r.str();
            } else if (key == "ok") {
                if (seen & 8u) r.refuse("duplicate_field");
                seen |= 8u;
                v.ok = r.boolean();
            } else if (key == "payload") {
                if (seen & 16u) r.refuse("duplicate_field");
                seen |= 16u;
                v.payload = r.raw_value();
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 31u) != 31u) r.refuse("missing_field");
    return v;
}

inline OAServiceError decode_oaserviceerror(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OAServiceError v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "code") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.code = r.str();
            } else if (key == "message") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.message = r.str();
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 3u) != 3u) r.refuse("missing_field");
    return v;
}

inline OARouterModelsResult decode_oaroutermodelsresult(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OARouterModelsResult v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "value") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.value = decode_modelssnapshot(r);
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 1u) != 1u) r.refuse("missing_field");
    return v;
}

inline OARouterHostsResult decode_oarouterhostsresult(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OARouterHostsResult v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "value") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.value = decode_hostssnapshot(r);
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 1u) != 1u) r.refuse("missing_field");
    return v;
}

inline OARouterPickResult decode_oarouterpickresult(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OARouterPickResult v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "value") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.value = decode_pickresult(r);
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 1u) != 1u) r.refuse("missing_field");
    return v;
}

inline PickRequest decode(std::string_view data) {
    Reader r{data};
    r.skip_ws();
    PickRequest v = decode_pickrequest(r);
    r.skip_ws();
    if (r.pos < r.buf.size()) r.refuse("trailing_bytes");
    return v;
}

// kRefusals is in the order two of them are chosen between.
inline const std::vector<std::string> kRefusals = {"malformed", "bad_string", "number_spelling", "wrong_type", "bad_timestamp", "depth_exceeded", "duplicate_key", "duplicate_field", "unknown_field", "missing_field", "trailing_bytes"};

inline int refusal_rank(std::string_view word) {
    for (std::size_t i = 0; i < kRefusals.size(); ++i)
        if (kRefusals[i] == word) return static_cast<int>(i);
    return -1;
}

struct FrameWriter{virtual ~FrameWriter()=default;virtual void WriteFrame(std::string_view)=0;};
struct DispatchError:std::runtime_error{using std::runtime_error::runtime_error;};
inline OAServiceFrame service_payload(std::string_view frame){Reader r{frame};r.skip_ws();auto v=decode_oaserviceframe(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");if(v.version!=1)throw DispatchError("unknown_version");return v;}

struct FrameExchanger{virtual ~FrameExchanger()=default;virtual std::string ExchangeFrame(std::string_view)=0;};
struct ServiceError:std::runtime_error{std::string code,message;ServiceError(std::string c,std::string m):std::runtime_error(m.empty()?c:m),code(c),message(m){}};
inline Raw service_response(std::string_view frame,std::string_view service,std::string_view method){
 Reader r{frame};r.skip_ws();auto v=decode_oaservicereply(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");if(v.version!=1)throw DispatchError("unknown_version");if(v.service!=service||v.method!=method)throw DispatchError("mismatched_response");
 if(!v.ok){Reader e{v.payload};e.depth=1;e.skip_ws();auto error=decode_oaserviceerror(e);e.skip_ws();if(e.pos!=e.buf.size())e.refuse("trailing_bytes");if(error.code.empty())throw DispatchError("invalid_error");throw ServiceError(error.code,error.message);}return v.payload;
}
inline std::string service_reply(const OAServiceFrame& request,const Raw& payload,const ServiceError* error=nullptr){
 OAServiceReply reply;reply.version=1;reply.service=request.service;reply.method=request.method;reply.ok=error==nullptr;reply.payload=payload;
 if(error){OAServiceError e;e.code=error->code.empty()?"handler_error":error->code;e.message=error->message;reply.payload.clear();enc_oaserviceerror(reply.payload,e,1);}
 std::string frame;enc_oaservicereply(frame,reply,0);Reader r{frame};r.skip_ws();decode_oaservicereply(r);return frame;
}
struct Router{virtual ~Router()=default;
virtual ModelsSnapshot Models(const bool& arg0)=0;
virtual HostsSnapshot Hosts(const bool& arg0)=0;
virtual PickResult Pick(const PickRequest& arg0)=0;
};
template<class Transport>struct RouterClient:Router{Transport& transport_;explicit RouterClient(Transport&t):transport_(t){}
ModelsSnapshot Models(const bool& arg0)override{OARouterModelsArguments args;
args.fresh=arg0;
OAServiceFrame v;v.version=1;v.service="abstraction.router/router@1";v.method="Models";enc_oaroutermodelsarguments(v.arguments,args,1);std::string frame;enc_oaserviceframe(frame,v,0);service_payload(frame);
auto response=transport_.ExchangeFrame(frame);auto payload=service_response(response,v.service,v.method);Reader r{payload};r.depth=1;r.skip_ws();auto result=decode_oaroutermodelsresult(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");
return result.value;
}
HostsSnapshot Hosts(const bool& arg0)override{OARouterHostsArguments args;
args.fresh=arg0;
OAServiceFrame v;v.version=1;v.service="abstraction.router/router@1";v.method="Hosts";enc_oarouterhostsarguments(v.arguments,args,1);std::string frame;enc_oaserviceframe(frame,v,0);service_payload(frame);
auto response=transport_.ExchangeFrame(frame);auto payload=service_response(response,v.service,v.method);Reader r{payload};r.depth=1;r.skip_ws();auto result=decode_oarouterhostsresult(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");
return result.value;
}
PickResult Pick(const PickRequest& arg0)override{OARouterPickArguments args;
args.request=arg0;
OAServiceFrame v;v.version=1;v.service="abstraction.router/router@1";v.method="Pick";enc_oarouterpickarguments(v.arguments,args,1);std::string frame;enc_oaserviceframe(frame,v,0);service_payload(frame);
auto response=transport_.ExchangeFrame(frame);auto payload=service_response(response,v.service,v.method);Reader r{payload};r.depth=1;r.skip_ws();auto result=decode_oarouterpickresult(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");
return result.value;
}
};
struct RouterService{inline static constexpr std::string_view wire_name="abstraction.router/router@1";inline static constexpr std::string_view capability="abstraction.router";template<class Transport>using Client=RouterClient<Transport>;};
struct RouterDispatcher:FrameWriter,FrameExchanger{Router&handler;explicit RouterDispatcher(Router&h):handler(h){}
void WriteFrame(std::string_view frame)override{auto v=service_payload(frame);if(v.service!="abstraction.router/router@1")throw DispatchError("unknown_service");
if(v.method=="Models"){
throw DispatchError("wrong_mode");}
if(v.method=="Hosts"){
throw DispatchError("wrong_mode");}
if(v.method=="Pick"){
throw DispatchError("wrong_mode");}
throw DispatchError("unknown_method");}
std::string ExchangeFrame(std::string_view frame)override{auto v=service_payload(frame);if(v.service!="abstraction.router/router@1"){ServiceError e("unknown_service","");return service_reply(v,"",&e);}
try{
if(v.method=="Models"){
Reader r{v.arguments};r.depth=1;r.skip_ws();auto args=decode_oaroutermodelsarguments(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");auto payload=invoke_Models(args);return service_reply(v,payload);}
if(v.method=="Hosts"){
Reader r{v.arguments};r.depth=1;r.skip_ws();auto args=decode_oarouterhostsarguments(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");auto payload=invoke_Hosts(args);return service_reply(v,payload);}
if(v.method=="Pick"){
Reader r{v.arguments};r.depth=1;r.skip_ws();auto args=decode_oarouterpickarguments(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");auto payload=invoke_Pick(args);return service_reply(v,payload);}
throw ServiceError("unknown_method","");}catch(const ServiceError&e){return service_reply(v,"",&e);}catch(const Refusal&e){ServiceError error(e.word,"");return service_reply(v,"",&error);}
}
Raw invoke_Models(const OARouterModelsArguments&args){
ModelsSnapshot result{};
try{
result=handler.Models(args.fresh);
}catch(const ServiceError&){throw;}catch(...){throw ServiceError("handler_error","handler failed");}
try{
OARouterModelsResult value;
value.value=result;
Raw payload;enc_oaroutermodelsresult(payload,value,1);Reader r{payload};r.depth=1;r.skip_ws();decode_oaroutermodelsresult(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");return payload;
}catch(...){throw ServiceError("invalid_result","");}
}
Raw invoke_Hosts(const OARouterHostsArguments&args){
HostsSnapshot result{};
try{
result=handler.Hosts(args.fresh);
}catch(const ServiceError&){throw;}catch(...){throw ServiceError("handler_error","handler failed");}
try{
OARouterHostsResult value;
value.value=result;
Raw payload;enc_oarouterhostsresult(payload,value,1);Reader r{payload};r.depth=1;r.skip_ws();decode_oarouterhostsresult(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");return payload;
}catch(...){throw ServiceError("invalid_result","");}
}
Raw invoke_Pick(const OARouterPickArguments&args){
PickResult result{};
try{
result=handler.Pick(args.request);
}catch(const ServiceError&){throw;}catch(...){throw ServiceError("handler_error","handler failed");}
try{
OARouterPickResult value;
value.value=result;
Raw payload;enc_oarouterpickresult(payload,value,1);Reader r{payload};r.depth=1;r.skip_ws();decode_oarouterpickresult(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");return payload;
}catch(...){throw ServiceError("invalid_result","");}
}
};

}  // namespace abstraction::router
