// Code generated by abstraction-idl from abstraction-router/router.thrift. DO NOT EDIT.

const HEX = "0123456789abcdef";
const ENC = new TextEncoder();
const SHORT = { 0x22: '\\"', 0x5c: "\\\\", 0x08: "\\b", 0x0c: "\\f", 0x0a: "\\n", 0x0d: "\\r", 0x09: "\\t" };

export class Out {
  constructor() { this.b = []; }
  byte(c) { this.b.push(c); }
  ascii(s) { for (let i = 0; i < s.length; i++) this.b.push(s.charCodeAt(i)); }
  bytes() { return Uint8Array.from(this.b); }
}

function escByte(out, c) {
  const short = SHORT[c];
  if (short !== undefined) out.ascii(short);
  else if (c < 0x20) out.ascii("\\u00" + HEX[c >> 4] + HEX[c & 0xf]);
  else out.byte(c);
}

// Every integer the definition calls i64 is a BigInt here, because Number
// rounds above 2^53 and two values in the conformance record are i64 extremes.
export function num(out, n) { out.ascii(BigInt(n).toString()); }

export function pad(out, depth) { for (let i = 0; i < depth * 2; i++) out.byte(0x20); }

export function strs(out, v, depth) {
  if (v.length === 0) { out.ascii("[]"); return; }
  out.ascii("[\n");
  for (let i = 0; i < v.length; i++) {
    pad(out, depth + 1);
    esc(out, v[i]);
    if (i + 1 < v.length) out.byte(0x2c);
    out.byte(0x0a);
  }
  pad(out, depth);
  out.byte(0x5d);
}

const isWs = (c) => c === 0x20 || c === 0x09 || c === 0x0a || c === 0x0d;

export function raw(out, s, depth) {
  const b = typeof s === "string" ? ENC.encode(s) : s;
  let i = 0;
  while (i < b.length) {
    const c = b[i];
    if (isWs(c)) { i++; continue; }
    if (c === 0x22) {
      let j = i + 1;
      while (j < b.length) {
        if (b[j] === 0x5c) { j += 2; continue; }
        if (b[j] === 0x22) { j++; break; }
        j++;
      }
      for (let k = i; k < j; k++) out.byte(b[k]);
      i = j;
    } else if (c === 0x7b || c === 0x5b) {
      out.byte(c);
      i++;
      let j = i;
      while (j < b.length && isWs(b[j])) j++;
      if (j < b.length && (b[j] === 0x7d || b[j] === 0x5d)) { out.byte(b[j]); i = j + 1; }
      else { depth++; out.byte(0x0a); pad(out, depth); }
    } else if (c === 0x7d || c === 0x5d) {
      depth--;
      out.byte(0x0a);
      pad(out, depth);
      out.byte(c);
      i++;
    } else if (c === 0x2c) {
      out.ascii(",\n");
      pad(out, depth);
      i++;
    } else if (c === 0x3a) {
      out.ascii(": ");
      i++;
    } else {
      out.byte(c);
      i++;
    }
  }
}

// A JavaScript string sorts by UTF-16 code unit, which puts U+1D11E before
// U+FFFD where every other target puts it after. The definition declares UTF-8
// byte order, so the comparison is done on the encoded bytes.
function byteLess(a, b) {
  const x = ENC.encode(a), y = ENC.encode(b);
  const n = Math.min(x.length, y.length);
  for (let i = 0; i < n; i++) if (x[i] !== y[i]) return x[i] - y[i];
  return x.length - y.length;
}

export function rawmap(out, m, depth) {
  const keys = Object.keys(m).sort(byteLess);
  if (keys.length === 0) { out.ascii("{}"); return; }
  out.ascii("{\n");
  for (let i = 0; i < keys.length; i++) {
    pad(out, depth + 1);
    esc(out, keys[i]);
    out.ascii(": ");
    raw(out, m[keys[i]], depth + 1);
    if (i + 1 < keys.length) out.byte(0x2c);
    out.byte(0x0a);
  }
  pad(out, depth);
  out.byte(0x7d);
}

export function esc(out, s) {
  out.byte(0x22);
  for (const c of ENC.encode(s)) escByte(out, c);
  out.byte(0x22);
}

export function encList(out, v, depth, enc) {
  if (v.length === 0) { out.ascii("[]"); return; }
  out.ascii("[\n");
  for (let i = 0; i < v.length; i++) {
    pad(out, depth + 1);
    enc(out, v[i], depth + 1);
    if (i + 1 < v.length) out.byte(0x2c);
    out.byte(0x0a);
  }
  pad(out, depth);
  out.byte(0x5d);
}

export const verdicts = ["resident", "would-load", "unservable", "not-here", "unparseable", "unauthorised"];

export function enc_hostallowance(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "hosts");
  out.ascii(": ");
  strs(out, v.hosts, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_pickrequest(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "model");
  out.ascii(": ");
  esc(out, v.model);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "fresh");
  out.ascii(": ");
  out.ascii(v.fresh ? "true" : "false");
  if (v.allowed !== undefined && v.allowed !== null) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "allowed");
    out.ascii(": ");
    enc_hostallowance(out, v.allowed, depth + 1);
  }
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_caller(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "user_description");
  out.ascii(": ");
  esc(out, v.user_description);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "path_description");
  out.ascii(": ");
  esc(out, v.path_description);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_observation(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "caller");
  out.ascii(": ");
  enc_caller(out, v.caller, depth + 1);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "took_ms");
  out.ascii(": ");
  num(out, v.took_ms);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "cache_age_ms");
  out.ascii(": ");
  num(out, v.cache_age_ms);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_alias(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "host");
  out.ascii(": ");
  esc(out, v.host);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "name");
  out.ascii(": ");
  esc(out, v.name);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "resident");
  out.ascii(": ");
  out.ascii(v.resident ? "true" : "false");
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "servable");
  out.ascii(": ");
  out.ascii(v.servable ? "true" : "false");
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_family(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "family");
  out.ascii(": ");
  esc(out, v.family);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "names");
  out.ascii(": ");
  encList(out, v.names, depth + 1, enc_alias);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_modelssnapshot(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "observation");
  out.ascii(": ");
  enc_observation(out, v.observation, depth + 1);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "models");
  out.ascii(": ");
  encList(out, v.models, depth + 1, enc_family);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_hoststate(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "host");
  out.ascii(": ");
  esc(out, v.host);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "base");
  out.ascii(": ");
  esc(out, v.base);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "up");
  out.ascii(": ");
  out.ascii(v.up ? "true" : "false");
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "why");
  out.ascii(": ");
  esc(out, v.why);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "installed");
  out.ascii(": ");
  num(out, v.installed);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "resident");
  out.ascii(": ");
  strs(out, v.resident, depth + 1);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "servable");
  out.ascii(": ");
  out.ascii(v.servable ? "true" : "false");
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_ask(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "at");
  out.ascii(": ");
  esc(out, writeTimestamp(v.at));
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "caller");
  out.ascii(": ");
  esc(out, v.caller);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "user");
  out.ascii(": ");
  esc(out, v.user);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "model");
  out.ascii(": ");
  esc(out, v.model);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "family");
  out.ascii(": ");
  esc(out, v.family);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "verdict");
  out.ascii(": ");
  esc(out, v.verdict);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "host");
  out.ascii(": ");
  esc(out, v.host);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_hostssnapshot(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "observation");
  out.ascii(": ");
  enc_observation(out, v.observation, depth + 1);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "hosts");
  out.ascii(": ");
  encList(out, v.hosts, depth + 1, enc_hoststate);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "doubled");
  out.ascii(": ");
  strs(out, v.doubled, depth + 1);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "asked");
  out.ascii(": ");
  encList(out, v.asked, depth + 1, enc_ask);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_decision(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "asked");
  out.ascii(": ");
  esc(out, v.asked);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "family");
  out.ascii(": ");
  esc(out, v.family);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "verdict");
  out.ascii(": ");
  esc(out, v.verdict);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "host");
  out.ascii(": ");
  esc(out, v.host);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "model");
  out.ascii(": ");
  esc(out, v.model);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "endpoint");
  out.ascii(": ");
  esc(out, v.endpoint);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "installed_on");
  out.ascii(": ");
  strs(out, v.installed_on, depth + 1);
  if (v.authorised !== undefined && v.authorised !== null) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "authorised");
    out.ascii(": ");
    enc_hostallowance(out, v.authorised, depth + 1);
  }
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "withheld");
  out.ascii(": ");
  strs(out, v.withheld, depth + 1);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "loads");
  out.ascii(": ");
  num(out, v.loads);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "why");
  out.ascii(": ");
  esc(out, v.why);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_pickresult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "observation");
  out.ascii(": ");
  enc_observation(out, v.observation, depth + 1);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "decision");
  out.ascii(": ");
  enc_decision(out, v.decision, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oaroutermodelsarguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "fresh");
  out.ascii(": ");
  out.ascii(v.fresh ? "true" : "false");
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oarouterhostsarguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "fresh");
  out.ascii(": ");
  out.ascii(v.fresh ? "true" : "false");
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oarouterpickarguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "request");
  out.ascii(": ");
  enc_pickrequest(out, v.request, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oaserviceframe(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "version");
  out.ascii(": ");
  num(out, v.version);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "service");
  out.ascii(": ");
  esc(out, v.service);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "method");
  out.ascii(": ");
  esc(out, v.method);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "arguments");
  out.ascii(": ");
  for (const byte of (typeof v.arguments === "string" ? ENC.encode(v.arguments) : v.arguments)) out.byte(byte);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oaservicereply(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "version");
  out.ascii(": ");
  num(out, v.version);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "service");
  out.ascii(": ");
  esc(out, v.service);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "method");
  out.ascii(": ");
  esc(out, v.method);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "ok");
  out.ascii(": ");
  out.ascii(v.ok ? "true" : "false");
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "payload");
  out.ascii(": ");
  for (const byte of (typeof v.payload === "string" ? ENC.encode(v.payload) : v.payload)) out.byte(byte);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oaserviceerror(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "code");
  out.ascii(": ");
  esc(out, v.code);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "message");
  out.ascii(": ");
  esc(out, v.message);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oaroutermodelsresult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  enc_modelssnapshot(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oarouterhostsresult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  enc_hostssnapshot(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oarouterpickresult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  enc_pickresult(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function encode(v) {
  const out = new Out();
  enc_pickrequest(out, v, 0);
  out.byte(0x0a);
  return out.bytes();
}

// A BOM inside a JSON string is data, not a stream signature.
const DEC = new TextDecoder("utf-8", {ignoreBOM: true});
const DEPTH_LIMIT = 64;
const I64_DIGITS = 19;
const UNESCAPE = { 0x22: 0x22, 0x5c: 0x5c, 0x2f: 0x2f, 0x62: 0x08, 0x66: 0x0c, 0x6e: 0x0a, 0x72: 0x0d, 0x74: 0x09 };

export class Refusal extends Error {
  constructor(word, offset) {
    super("refused: " + word + " at byte " + offset);
    this.name = "Refusal";
    this.word = word;
    this.offset = offset;
  }
}

function appendRune(out, cp) {
  if (cp < 0x80) out.push(cp);
  else if (cp < 0x800) out.push(0xc0 | (cp >> 6), 0x80 | (cp & 0x3f));
  else if (cp < 0x10000) out.push(0xe0 | (cp >> 12), 0x80 | ((cp >> 6) & 0x3f), 0x80 | (cp & 0x3f));
  else out.push(0xf0 | (cp >> 18), 0x80 | ((cp >> 12) & 0x3f), 0x80 | ((cp >> 6) & 0x3f), 0x80 | (cp & 0x3f));
}

// TextDecoder substitutes U+FFFD for a bad sequence rather than reporting it, so
// the bytes are checked before they are decoded and the refusal says so.
function validUtf8(b) {
  for (let i = 0; i < b.length; ) {
    const c = b[i];
    if (c < 0x80) { i++; continue; }
    let n, cp;
    if (c >> 5 === 0x6) { n = 2; cp = c & 0x1f; }
    else if (c >> 4 === 0xe) { n = 3; cp = c & 0x0f; }
    else if (c >> 3 === 0x1e) { n = 4; cp = c & 0x07; }
    else return false;
    if (i + n > b.length) return false;
    for (let k = 1; k < n; k++) {
      if (b[i + k] >> 6 !== 0x2) return false;
      cp = (cp << 6) | (b[i + k] & 0x3f);
    }
    const lowest = [0, 0, 0x80, 0x800, 0x10000][n];
    if (cp < lowest || cp > 0x10ffff || (cp >= 0xd800 && cp <= 0xdfff)) return false;
    i += n;
  }
  return true;
}

class Reader {
  constructor(buf) { this.buf = buf; this.pos = 0; this.depth = 0; }

  refuse(word) { return new Refusal(word, this.pos); }

  at() { return this.pos < this.buf.length ? this.buf[this.pos] : 0; }

  digit() { const c = this.at(); return c >= 0x30 && c <= 0x39; }

  ws() { while (this.pos < this.buf.length && isWs(this.buf[this.pos])) this.pos++; }

  enter() {
    this.depth++;
    if (this.depth > DEPTH_LIMIT) throw this.refuse("depth_exceeded");
  }

  string() {
    if (this.at() !== 0x22) throw this.refuse("wrong_type");
    this.pos++;
    const out = [];
    for (;;) {
      if (this.pos >= this.buf.length) throw this.refuse("malformed");
      const c = this.buf[this.pos];
      if (c === 0x22) {
        this.pos++;
        const bytes = Uint8Array.from(out);
        if (!validUtf8(bytes)) throw this.refuse("bad_string");
        return DEC.decode(bytes);
      }
      if (c < 0x20) throw this.refuse("bad_string");
      if (c === 0x5c) this.escape(out);
      else { out.push(c); this.pos++; }
    }
  }

  escape(out) {
    this.pos++;
    if (this.pos >= this.buf.length) throw this.refuse("malformed");
    const c = this.buf[this.pos];
    this.pos++;
    const plain = UNESCAPE[c];
    if (plain !== undefined) { out.push(plain); return; }
    if (c !== 0x75) throw this.refuse("bad_string");
    let u = this.hex4();
    if (u >= 0xdc00 && u <= 0xdfff) throw this.refuse("bad_string");
    if (u >= 0xd800 && u <= 0xdbff) {
      if (this.pos + 1 >= this.buf.length || this.buf[this.pos] !== 0x5c || this.buf[this.pos + 1] !== 0x75)
        throw this.refuse("bad_string");
      this.pos += 2;
      const low = this.hex4();
      if (low < 0xdc00 || low > 0xdfff) throw this.refuse("bad_string");
      u = 0x10000 + ((u - 0xd800) << 10) + (low - 0xdc00);
    }
    appendRune(out, u);
  }

  hex4() {
    if (this.pos + 4 > this.buf.length) throw this.refuse("bad_string");
    let u = 0;
    for (let i = 0; i < 4; i++) {
      const c = this.buf[this.pos + i];
      if (c >= 0x30 && c <= 0x39) u = (u << 4) | (c - 0x30);
      else if (c >= 0x61 && c <= 0x66) u = (u << 4) | (c - 0x61 + 10);
      else if (c >= 0x41 && c <= 0x46) u = (u << 4) | (c - 0x41 + 10);
      else throw this.refuse("bad_string");
    }
    this.pos += 4;
    return u;
  }

  integer(low, high) {
    const c = this.at();
    if (c !== 0x2d && (c < 0x30 || c > 0x39)) throw this.refuse("wrong_type");
    const negative = c === 0x2d;
    if (negative) this.pos++;
    if (!this.digit()) throw this.refuse("malformed");
    const start = this.pos;
    if (this.at() === 0x30) this.pos++;
    else while (this.digit()) this.pos++;
    const after = this.at();
    if (after === 0x2e || after === 0x65 || after === 0x45 || this.digit()) throw this.refuse("number_spelling");
    if (this.pos - start > I64_DIGITS) throw this.refuse("number_spelling");
    let n = BigInt(String.fromCharCode(...this.buf.subarray(start, this.pos)));
    if (negative) {
      if (n === 0n) throw this.refuse("number_spelling");
      n = -n;
    }
    if (n < low || n > high) throw this.refuse("number_spelling");
    return n;
  }

  boolean() {
    if (this.at() === 0x74) { this.literal("true"); return true; }
    if (this.at() === 0x66) { this.literal("false"); return false; }
    throw this.refuse("wrong_type");
  }

  literal(word) {
    for (let i = 0; i < word.length; i++)
      if (this.buf[this.pos + i] !== word.charCodeAt(i)) throw this.refuse("malformed");
    this.pos += word.length;
  }

  strList() {
    if (this.at() !== 0x5b) throw this.refuse("wrong_type");
    this.enter();
    this.pos++;
    const out = [];
    this.ws();
    if (this.at() !== 0x5d) {
      for (;;) {
        this.ws();
        out.push(this.string());
        this.ws();
        if (this.at() !== 0x2c) break;
        this.pos++;
      }
    }
    if (this.at() !== 0x5d) throw this.refuse("malformed");
    this.pos++;
    this.depth--;
    return out;
  }

  rawMap() {
    if (this.at() !== 0x7b) throw this.refuse("wrong_type");
    this.enter();
    this.pos++;
    const out = Object.create(null);
    this.ws();
    if (this.at() !== 0x7d) {
      for (;;) {
        this.ws();
        if (this.at() !== 0x22) throw this.refuse("malformed");
        const k = this.string();
        if (k in out) throw this.refuse("duplicate_key");
        this.ws();
        if (this.at() !== 0x3a) throw this.refuse("malformed");
        this.pos++;
        this.ws();
        out[k] = this.rawValue();
        this.ws();
        if (this.at() !== 0x2c) break;
        this.pos++;
      }
    }
    if (this.at() !== 0x7d) throw this.refuse("malformed");
    this.pos++;
    this.depth--;
    return out;
  }

  rawValue() {
    const start = this.pos;
    this.skipValue();
    return this.buf.subarray(start, this.pos);
  }

  skipValue() {
    const c = this.at();
    if (c === 0x22) this.skipString();
    else if (c === 0x7b || c === 0x5b) this.skipContainer();
    else if (c === 0x74) this.literal("true");
    else if (c === 0x66) this.literal("false");
    else if (c === 0x6e) this.literal("null");
    else if (c === 0x2d || (c >= 0x30 && c <= 0x39)) this.skipNumber();
    else throw this.refuse("malformed");
  }

  // An opaque value is validated and carried, never interpreted. Its syntax is
  // the record's own — the same string reader, so an escape, a control byte or a
  // lone surrogate is judged identically at any depth — and what it is free to
  // spell, it keeps: the bytes between these two offsets are what a writer
  // re-emits. A number is walked, never converted, so a value no host type holds
  // survives the reader that carried it.
  skipString() {
    this.string();
  }

  someDigits() {
    let n = 0;
    while (this.at() >= 0x30 && this.at() <= 0x39) { this.pos++; n++; }
    if (n === 0) throw this.refuse("number_spelling");
  }

  skipNumber() {
    if (this.at() === 0x2d) this.pos++;
    const c = this.at();
    if (c === 0x30) this.pos++;
    else if (c > 0x30 && c <= 0x39) { while (this.at() >= 0x30 && this.at() <= 0x39) this.pos++; }
    else throw this.refuse("number_spelling");
    if (this.at() === 0x2e) { this.pos++; this.someDigits(); }
    if (this.at() === 0x65 || this.at() === 0x45) {
      this.pos++;
      if (this.at() === 0x2b || this.at() === 0x2d) this.pos++;
      this.someDigits();
    }
  }

  skipContainer() {
    const opener = this.at();
    const shut = opener === 0x7b ? 0x7d : 0x5d;
    this.enter();
    this.pos++;
    this.ws();
    const seen = new Set();
    if (this.at() !== shut) {
      for (;;) {
        this.ws();
        if (opener === 0x7b) {
          if (this.at() !== 0x22) throw this.refuse("malformed");
          const k = this.string();
          if (seen.has(k)) throw this.refuse("duplicate_key");
          seen.add(k);
          this.ws();
          if (this.at() !== 0x3a) throw this.refuse("malformed");
          this.pos++;
          this.ws();
        }
        this.skipValue();
        this.ws();
        if (this.at() !== 0x2c) break;
        this.pos++;
      }
    }
    if (this.at() !== shut) throw this.refuse("malformed");
    this.pos++;
    this.depth--;
  }
}

function decodeList(r, elem) {
  if (r.at() !== 0x5b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const out = [];
  r.ws();
  if (r.at() !== 0x5d) {
    for (;;) {
      r.ws();
      out.push(elem(r));
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x5d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  return out;
}

const isDigits = (s, i, n) => {
  if (s.length < i + n) return false;
  for (let k = 0; k < n; k++) if (s[i + k] < "0" || s[i + k] > "9") return false;
  return true;
};

const datePart = (s) =>
  s.length >= 19 && isDigits(s, 0, 4) && s[4] === "-" && isDigits(s, 5, 2) && s[7] === "-" &&
  isDigits(s, 8, 2) && isDigits(s, 11, 2) && s[13] === ":" && isDigits(s, 14, 2) && s[16] === ":" &&
  isDigits(s, 17, 2);

// [DEF-G1] rfc3339-wide: what a reader accepts. Any fraction of one to nine
// digits or none, either case of the separators, and a numeric offset.
function lexicalTimestamp(s) {
  if (!datePart(s) || (s[10] !== "T" && s[10] !== "t")) return false;
  let i = 19;
  if (i < s.length && s[i] === ".") {
    i++;
    const start = i;
    while (i < s.length && s[i] >= "0" && s[i] <= "9") i++;
    if (i - start < 1 || i - start > 9) return false;
  }
  if (i >= s.length) return false;
  if (s[i] === "Z" || s[i] === "z") return i + 1 === s.length;
  if (s[i] !== "+" && s[i] !== "-") return false;
  return s.length === i + 6 && isDigits(s, i + 1, 2) && s[i + 3] === ":" && isDigits(s, i + 4, 2);
}

// [DEF-G2] rfc3339-micros: what a writer emits. Exactly six fractional digits,
// upper-case separators, UTC.
export function microsTimestamp(s) {
  return s.length === 27 && normalizedTimestamp(s) === s;
}

function readTimestamp(r) {
  const at = r.pos;
  const s = r.string();
  if (!wideTimestamp(s)) {
    r.pos = at;
    throw r.refuse("bad_timestamp");
  }
  return s;
}

function timestampDays(y, m) {
  if (m === 2) return y % 4 === 0 && (y % 100 !== 0 || y % 400 === 0) ? 29 : 28;
  return [4, 6, 9, 11].includes(m) ? 30 : 31;
}
function normalizedTimestamp(s) {
  if (!lexicalTimestamp(s)) return "";
  let y=Number(s.slice(0,4)), m=Number(s.slice(5,7)), d=Number(s.slice(8,10));
  const h=Number(s.slice(11,13)), minute=Number(s.slice(14,16)), sec=Number(s.slice(17,19));
  if (m<1 || m>12 || d<1 || d>timestampDays(y,m) || h>23 || minute>59 || sec>59) return "";
  let i=19, fraction="";
  if (s[i]===".") { const start=++i; while(s[i]>="0" && s[i]<="9") i++; fraction=s.slice(start,i); }
  let total=h*60+minute;
  if(s[i]==="+" || s[i]==="-") {
    const oh=Number(s.slice(i+1,i+3)), om=Number(s.slice(i+4,i+6));
    if(oh>23 || om>59) return "";
    total += (s[i]==="+" ? -1 : 1)*(oh*60+om);
  }
  if(total<0) {total+=1440; d--;} else if(total>=1440) {total-=1440; d++;}
  if(d===0) {m--; if(m===0) {y--; m=12;} d=timestampDays(y,m);}
  if(d>timestampDays(y,m)) {d=1; m++; if(m===13) {y++; m=1;}}
  if(y<0 || y>9999) return "";
  const pad=(n,w)=>String(n).padStart(w,"0");
  return pad(y,4)+"-"+pad(m,2)+"-"+pad(d,2)+"T"+pad(Math.floor(total/60),2)+":"+pad(total%60,2)+":"+pad(sec,2)+"."+(fraction+"000000").slice(0,6)+"Z";
}
export function wideTimestamp(s) { return normalizedTimestamp(s)!==""; }
function writeTimestamp(s) {
  const result=normalizedTimestamp(s);
  if(result==="") throw new Refusal("bad_timestamp",0);
  return result;
}

export function newHostAllowance() {
  return { hosts: [] };
}

export function newPickRequest() {
  return { model: "", fresh: false, allowed: null };
}

export function newCaller() {
  return { user_description: "", path_description: "" };
}

export function newObservation() {
  return { caller: newCaller(), took_ms: 0n, cache_age_ms: 0n };
}

export function newAlias() {
  return { host: "", name: "", resident: false, servable: false };
}

export function newFamily() {
  return { family: "", names: [] };
}

export function newModelsSnapshot() {
  return { observation: newObservation(), models: [] };
}

export function newHostState() {
  return { host: "", base: "", up: false, why: "", installed: 0n, resident: [], servable: false };
}

export function newAsk() {
  return { at: "", caller: "", user: "", model: "", family: "", verdict: "", host: "" };
}

export function newHostsSnapshot() {
  return { observation: newObservation(), hosts: [], doubled: [], asked: [] };
}

export function newDecision() {
  return { asked: "", family: "", verdict: "", host: "", model: "", endpoint: "", installed_on: [], authorised: null, withheld: [], loads: 0n, why: "" };
}

export function newPickResult() {
  return { observation: newObservation(), decision: newDecision() };
}

export function newOARouterModelsArguments() {
  return { fresh: false };
}

export function newOARouterHostsArguments() {
  return { fresh: false };
}

export function newOARouterPickArguments() {
  return { request: newPickRequest() };
}

export function newOAServiceFrame() {
  return { version: 0, service: "", method: "", arguments: "" };
}

export function newOAServiceReply() {
  return { version: 0, service: "", method: "", ok: false, payload: "" };
}

export function newOAServiceError() {
  return { code: "", message: "" };
}

export function newOARouterModelsResult() {
  return { value: newModelsSnapshot() };
}

export function newOARouterHostsResult() {
  return { value: newHostsSnapshot() };
}

export function newOARouterPickResult() {
  return { value: newPickResult() };
}

function decode_hostallowance(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newHostAllowance();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "hosts") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.hosts = r.strList();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function decode_pickrequest(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newPickRequest();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "model") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.model = r.string();
      } else if (key === "fresh") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.fresh = r.boolean();
      } else if (key === "allowed") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.allowed = decode_hostallowance(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
  return v;
}

function decode_caller(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newCaller();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "user_description") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.user_description = r.string();
      } else if (key === "path_description") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.path_description = r.string();
      } else {
        r.skipValue();
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
  return v;
}

function decode_observation(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newObservation();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "caller") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.caller = decode_caller(r);
      } else if (key === "took_ms") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.took_ms = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else if (key === "cache_age_ms") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.cache_age_ms = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else {
        r.skipValue();
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 7) >>> 0) !== 7) throw r.refuse("missing_field");
  return v;
}

function decode_alias(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newAlias();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "host") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.host = r.string();
      } else if (key === "name") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.name = r.string();
      } else if (key === "resident") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.resident = r.boolean();
      } else if (key === "servable") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.servable = r.boolean();
      } else {
        r.skipValue();
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 15) >>> 0) !== 15) throw r.refuse("missing_field");
  return v;
}

function decode_family(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newFamily();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "family") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.family = r.string();
      } else if (key === "names") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.names = decodeList(r, decode_alias);
      } else {
        r.skipValue();
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
  return v;
}

function decode_modelssnapshot(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newModelsSnapshot();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "observation") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.observation = decode_observation(r);
      } else if (key === "models") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.models = decodeList(r, decode_family);
      } else {
        r.skipValue();
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
  return v;
}

function decode_hoststate(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newHostState();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "host") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.host = r.string();
      } else if (key === "base") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.base = r.string();
      } else if (key === "up") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.up = r.boolean();
      } else if (key === "why") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.why = r.string();
      } else if (key === "installed") {
        if (seen & 16) throw r.refuse("duplicate_field");
        seen |= 16;
        v.installed = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else if (key === "resident") {
        if (seen & 32) throw r.refuse("duplicate_field");
        seen |= 32;
        v.resident = r.strList();
      } else if (key === "servable") {
        if (seen & 64) throw r.refuse("duplicate_field");
        seen |= 64;
        v.servable = r.boolean();
      } else {
        r.skipValue();
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 127) >>> 0) !== 127) throw r.refuse("missing_field");
  return v;
}

function decode_ask(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newAsk();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "at") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.at = readTimestamp(r);
      } else if (key === "caller") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.caller = r.string();
      } else if (key === "user") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.user = r.string();
      } else if (key === "model") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.model = r.string();
      } else if (key === "family") {
        if (seen & 16) throw r.refuse("duplicate_field");
        seen |= 16;
        v.family = r.string();
      } else if (key === "verdict") {
        if (seen & 32) throw r.refuse("duplicate_field");
        seen |= 32;
        v.verdict = r.string();
      } else if (key === "host") {
        if (seen & 64) throw r.refuse("duplicate_field");
        seen |= 64;
        v.host = r.string();
      } else {
        r.skipValue();
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 127) >>> 0) !== 127) throw r.refuse("missing_field");
  return v;
}

function decode_hostssnapshot(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newHostsSnapshot();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "observation") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.observation = decode_observation(r);
      } else if (key === "hosts") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.hosts = decodeList(r, decode_hoststate);
      } else if (key === "doubled") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.doubled = r.strList();
      } else if (key === "asked") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.asked = decodeList(r, decode_ask);
      } else {
        r.skipValue();
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 15) >>> 0) !== 15) throw r.refuse("missing_field");
  return v;
}

function decode_decision(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newDecision();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "asked") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.asked = r.string();
      } else if (key === "family") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.family = r.string();
      } else if (key === "verdict") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.verdict = r.string();
      } else if (key === "host") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.host = r.string();
      } else if (key === "model") {
        if (seen & 16) throw r.refuse("duplicate_field");
        seen |= 16;
        v.model = r.string();
      } else if (key === "endpoint") {
        if (seen & 32) throw r.refuse("duplicate_field");
        seen |= 32;
        v.endpoint = r.string();
      } else if (key === "installed_on") {
        if (seen & 64) throw r.refuse("duplicate_field");
        seen |= 64;
        v.installed_on = r.strList();
      } else if (key === "authorised") {
        if (seen & 128) throw r.refuse("duplicate_field");
        seen |= 128;
        v.authorised = decode_hostallowance(r);
      } else if (key === "withheld") {
        if (seen & 256) throw r.refuse("duplicate_field");
        seen |= 256;
        v.withheld = r.strList();
      } else if (key === "loads") {
        if (seen & 512) throw r.refuse("duplicate_field");
        seen |= 512;
        v.loads = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else if (key === "why") {
        if (seen & 1024) throw r.refuse("duplicate_field");
        seen |= 1024;
        v.why = r.string();
      } else {
        r.skipValue();
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1919) >>> 0) !== 1919) throw r.refuse("missing_field");
  return v;
}

function decode_pickresult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newPickResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "observation") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.observation = decode_observation(r);
      } else if (key === "decision") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.decision = decode_decision(r);
      } else {
        r.skipValue();
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
  return v;
}

function decode_oaroutermodelsarguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOARouterModelsArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "fresh") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.fresh = r.boolean();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function decode_oarouterhostsarguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOARouterHostsArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "fresh") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.fresh = r.boolean();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function decode_oarouterpickarguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOARouterPickArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "request") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.request = decode_pickrequest(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function decode_oaserviceframe(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAServiceFrame();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "version") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.version = Number(r.integer(-2147483648n, 2147483647n));
      } else if (key === "service") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.service = r.string();
      } else if (key === "method") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.method = r.string();
      } else if (key === "arguments") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.arguments = r.rawValue();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 15) >>> 0) !== 15) throw r.refuse("missing_field");
  return v;
}

function decode_oaservicereply(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAServiceReply();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "version") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.version = Number(r.integer(-2147483648n, 2147483647n));
      } else if (key === "service") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.service = r.string();
      } else if (key === "method") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.method = r.string();
      } else if (key === "ok") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.ok = r.boolean();
      } else if (key === "payload") {
        if (seen & 16) throw r.refuse("duplicate_field");
        seen |= 16;
        v.payload = r.rawValue();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 31) >>> 0) !== 31) throw r.refuse("missing_field");
  return v;
}

function decode_oaserviceerror(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAServiceError();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "code") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.code = r.string();
      } else if (key === "message") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.message = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
  return v;
}

function decode_oaroutermodelsresult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOARouterModelsResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = decode_modelssnapshot(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function decode_oarouterhostsresult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOARouterHostsResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = decode_hostssnapshot(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function decode_oarouterpickresult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOARouterPickResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = decode_pickresult(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

export function decode(data) {
  const r = new Reader(data);
  r.ws();
  const v = decode_pickrequest(r);
  r.ws();
  if (r.pos < r.buf.length) throw r.refuse("trailing_bytes");
  return v;
}

// refusals is in the order two of them are chosen between.
export const refusals = ["malformed", "bad_string", "number_spelling", "wrong_type", "bad_timestamp", "depth_exceeded", "duplicate_key", "duplicate_field", "unknown_field", "missing_field", "trailing_bytes"];

export function refusalRank(word) {
  return refusals.indexOf(word);
}

export class DispatchError extends Error {
  constructor(code) { super(code); this.name = "DispatchError"; this.code = code; }
}
export class ServiceError extends Error {
  constructor(code, message = "") { super(message || code); this.name = "ServiceError"; this.code = code; }
}
function _serviceDecode(decoder, frame, depth) {
  const reader = new Reader(typeof frame === "string" ? ENC.encode(frame) : frame);
  reader.depth = depth; reader.ws();
  const value = decoder(reader); reader.ws();
  if (reader.pos !== reader.buf.length) throw reader.refuse("trailing_bytes");
  return value;
}
function _serviceEncode(encoder, value, depth) {
  const out = new Out(); encoder(out, value, depth); return out.bytes();
}
function _serviceCheck(kind, value, depth = 0) {
  if (depth > DEPTH_LIMIT) throw new Refusal("depth_exceeded", 0);
  let valid = false;
  if (kind === "string") {
    valid = typeof value === "string";
    if (valid) for (const ch of value) {
      const cp = ch.codePointAt(0);
      if (cp >= 0xd800 && cp <= 0xdfff) throw new Refusal("bad_string", 0);
    }
  } else if (kind === "i32") {
    valid = typeof value === "number" && Number.isInteger(value) && value >= -2147483648 && value <= 2147483647;
  } else if (kind === "i64") {
    valid = typeof value === "bigint" && value >= -9223372036854775808n && value <= 9223372036854775807n;
  } else if (kind === "bool") valid = typeof value === "boolean";
  else if (kind === "json") {
    valid = typeof value === "string" || value instanceof Uint8Array;
    if (valid) { const r = new Reader(typeof value === "string" ? ENC.encode(value) : value); r.depth = depth; r.ws(); r.rawValue(); r.ws(); if (r.pos !== r.buf.length) throw r.refuse("trailing_bytes"); }
  } else if (kind.startsWith("list<")) {
    valid = Array.isArray(value);
    if (valid) for (const item of value) _serviceCheck(kind.slice(5,-1), item, depth + 1);
  } else if (kind.startsWith("map<string,")) {
    valid = value !== null && typeof value === "object" && !Array.isArray(value);
    if (valid) for (const [key,item] of Object.entries(value)) { _serviceCheck("string",key,depth+1); _serviceCheck(kind.slice(11,-1),item,depth+1); }
  } else {
    const fields = _serviceRecords[kind];
    valid = fields !== undefined && value !== null && typeof value === "object" && !Array.isArray(value);
    if (valid) for (const [name,type,omit] of fields) {
      if (!Object.hasOwn(value,name)) throw new Refusal("missing_field",0);
      const item = value[name];
      if (omit === "absent" && item === null) continue;
      _serviceCheck(type,item,depth+1);
    }
  }
  if (!valid) throw new Refusal("wrong_type", 0);
}

const _serviceRecords = Object.create(null);
_serviceRecords["HostAllowance"] = [["hosts","list<string>","never"],];
_serviceRecords["PickRequest"] = [["model","string","never"],["fresh","bool","never"],["allowed","HostAllowance","absent"],];
_serviceRecords["Caller"] = [["user_description","string","never"],["path_description","string","never"],];
_serviceRecords["Observation"] = [["caller","Caller","never"],["took_ms","i64","never"],["cache_age_ms","i64","never"],];
_serviceRecords["Alias"] = [["host","string","never"],["name","string","never"],["resident","bool","never"],["servable","bool","never"],];
_serviceRecords["Family"] = [["family","string","never"],["names","list<Alias>","never"],];
_serviceRecords["ModelsSnapshot"] = [["observation","Observation","never"],["models","list<Family>","never"],];
_serviceRecords["HostState"] = [["host","string","never"],["base","string","never"],["up","bool","never"],["why","string","never"],["installed","i64","never"],["resident","list<string>","never"],["servable","bool","never"],];
_serviceRecords["Ask"] = [["at","string","never"],["caller","string","never"],["user","string","never"],["model","string","never"],["family","string","never"],["verdict","string","never"],["host","string","never"],];
_serviceRecords["HostsSnapshot"] = [["observation","Observation","never"],["hosts","list<HostState>","never"],["doubled","list<string>","never"],["asked","list<Ask>","never"],];
_serviceRecords["Decision"] = [["asked","string","never"],["family","string","never"],["verdict","string","never"],["host","string","never"],["model","string","never"],["endpoint","string","never"],["installed_on","list<string>","never"],["authorised","HostAllowance","absent"],["withheld","list<string>","never"],["loads","i64","never"],["why","string","never"],];
_serviceRecords["PickResult"] = [["observation","Observation","never"],["decision","Decision","never"],];
_serviceRecords["OARouterModelsArguments"] = [["fresh","bool","never"],];
_serviceRecords["OARouterHostsArguments"] = [["fresh","bool","never"],];
_serviceRecords["OARouterPickArguments"] = [["request","PickRequest","never"],];
_serviceRecords["OAServiceFrame"] = [["version","i32","never"],["service","string","never"],["method","string","never"],["arguments","json","never"],];
_serviceRecords["OAServiceReply"] = [["version","i32","never"],["service","string","never"],["method","string","never"],["ok","bool","never"],["payload","json","never"],];
_serviceRecords["OAServiceError"] = [["code","string","never"],["message","string","never"],];
_serviceRecords["OARouterModelsResult"] = [["value","ModelsSnapshot","never"],];
_serviceRecords["OARouterHostsResult"] = [["value","HostsSnapshot","never"],];
_serviceRecords["OARouterPickResult"] = [["value","PickResult","never"],];

function _serviceRequest(service, method, argumentsBytes) {
  return _serviceEncode(enc_oaserviceframe, {
    version:1, service, method, arguments:new TextDecoder("utf-8",{fatal:true}).decode(argumentsBytes)
  },0);
}

function _serviceResponse(frame, service, method) {
  if (!(frame instanceof Uint8Array)) throw new TypeError("transport frame must be Uint8Array");
  const reply = _serviceDecode(decode_oaservicereply, frame, 0);
  if (reply.version !== 1) throw new DispatchError("unknown_version");
  if (reply.service !== service || reply.method !== method) throw new DispatchError("mismatched_response");
  if (!reply.ok) {
    const error = _serviceDecode(decode_oaserviceerror, reply.payload, 1);
    if (!error.code) throw new DispatchError("invalid_error");
    throw new ServiceError(error.code, error.message);
  }
  return reply.payload;
}

export class RouterClient {
  constructor(transport) { this._transport = transport; }
  async Models(arg0) {
    const args = newOARouterModelsArguments();
    args["fresh"] = arg0;
    _serviceCheck("OARouterModelsArguments", args);
    const payload = _serviceEncode(enc_oaroutermodelsarguments, args, 1);
    _serviceDecode(decode_oaroutermodelsarguments, payload, 1);
    const request = _serviceRequest("abstraction.router/router@1", "Models", payload);
    const reply = _serviceResponse(await this._transport.exchangeFrame(request), "abstraction.router/router@1", "Models");
    const result = _serviceDecode(decode_oaroutermodelsresult, reply, 1);
    return result.value;
  }
  async Hosts(arg0) {
    const args = newOARouterHostsArguments();
    args["fresh"] = arg0;
    _serviceCheck("OARouterHostsArguments", args);
    const payload = _serviceEncode(enc_oarouterhostsarguments, args, 1);
    _serviceDecode(decode_oarouterhostsarguments, payload, 1);
    const request = _serviceRequest("abstraction.router/router@1", "Hosts", payload);
    const reply = _serviceResponse(await this._transport.exchangeFrame(request), "abstraction.router/router@1", "Hosts");
    const result = _serviceDecode(decode_oarouterhostsresult, reply, 1);
    return result.value;
  }
  async Pick(arg0) {
    const args = newOARouterPickArguments();
    args["request"] = arg0;
    _serviceCheck("OARouterPickArguments", args);
    const payload = _serviceEncode(enc_oarouterpickarguments, args, 1);
    _serviceDecode(decode_oarouterpickarguments, payload, 1);
    const request = _serviceRequest("abstraction.router/router@1", "Pick", payload);
    const reply = _serviceResponse(await this._transport.exchangeFrame(request), "abstraction.router/router@1", "Pick");
    const result = _serviceDecode(decode_oarouterpickresult, reply, 1);
    return result.value;
  }
}
export const RouterService = Object.freeze({wireName:"abstraction.router/router@1",Client:RouterClient});
