# Code generated by abstraction-idl from abstraction-router/router.thrift. DO NOT EDIT.

"""abstraction.router: generated contract types, vocabularies and service clients."""

from ._codec import (
    Alias,
    Ask,
    CREDENTIAL_CONSUMERS,
    Caller,
    Decision,
    DispatchError,
    Family,
    HostAllowance,
    HostState,
    HostsSnapshot,
    ModelsSnapshot,
    Observation,
    PROFILES,
    PickRequest,
    PickResult,
    ROUTER_ERROR_CODES,
    Refusal,
    Router,
    RouterClient,
    ServiceError,
    ServiceErrorCode,
    VERDICTS,
    WIRE_KINDS,
    decode,
    encode,
)

__all__ = [
    "Alias",
    "Ask",
    "CREDENTIAL_CONSUMERS",
    "Caller",
    "Decision",
    "DispatchError",
    "Family",
    "HostAllowance",
    "HostState",
    "HostsSnapshot",
    "ModelsSnapshot",
    "Observation",
    "PROFILES",
    "PickRequest",
    "PickResult",
    "ROUTER_ERROR_CODES",
    "Refusal",
    "Router",
    "RouterClient",
    "ServiceError",
    "ServiceErrorCode",
    "VERDICTS",
    "WIRE_KINDS",
    "decode",
    "encode",
]

# Report every class and function as a member of this package, so help(),
# tracebacks and pickles name the import an application writes.
for _name in __all__:
    _value = globals()[_name]
    if isinstance(_value, type) or callable(_value):
        _value.__module__ = __name__
del _name, _value
