# Code generated by abstraction-idl from abstraction-router/router.thrift. DO NOT EDIT.

_HEX = b"0123456789abcdef"
_WS = (0x20, 0x09, 0x0A, 0x0D)
_SHORT = {0x22: b'\\"', 0x5C: b"\\\\", 0x08: b"\\b", 0x0C: b"\\f",
          0x0A: b"\\n", 0x0D: b"\\r", 0x09: b"\\t"}


def esc_byte(out, c):
    short = _SHORT.get(c)
    if short is not None:
        out += short
    elif c < 0x20:
        out += b"\\u00" + bytes([_HEX[c >> 4], _HEX[c & 0xF]])
    else:
        out.append(c)


def num(out, n):
    out += str(int(n)).encode("ascii")


def pad(out, depth):
    out += b" " * (depth * 2)


def strs(out, v, depth):
    if not v:
        out += b"[]"
        return
    out += b"[\n"
    for i, s in enumerate(v):
        pad(out, depth + 1)
        esc(out, s)
        if i + 1 < len(v):
            out += b","
        out += b"\n"
    pad(out, depth)
    out += b"]"


def raw(out, s, depth):
    b = s.encode("utf-8") if isinstance(s, str) else s
    i, n = 0, len(b)
    while i < n:
        c = b[i]
        if c in _WS:
            i += 1
        elif c == 0x22:
            j = i + 1
            while j < n:
                if b[j] == 0x5C:
                    j += 2
                    continue
                if b[j] == 0x22:
                    j += 1
                    break
                j += 1
            out += b[i:j]
            i = j
        elif c in (0x7B, 0x5B):
            out.append(c)
            i += 1
            j = i
            while j < n and b[j] in _WS:
                j += 1
            if j < n and b[j] in (0x7D, 0x5D):
                out.append(b[j])
                i = j + 1
            else:
                depth += 1
                out += b"\n"
                pad(out, depth)
        elif c in (0x7D, 0x5D):
            depth -= 1
            out += b"\n"
            pad(out, depth)
            out.append(c)
            i += 1
        elif c == 0x2C:
            out += b",\n"
            pad(out, depth)
            i += 1
        elif c == 0x3A:
            out += b": "
            i += 1
        else:
            out.append(c)
            i += 1


def rawmap(out, m, depth):
    keys = sorted(m, key=lambda k: k.encode("utf-8"))
    if not keys:
        out += b"{}"
        return
    out += b"{\n"
    for i, k in enumerate(keys):
        pad(out, depth + 1)
        esc(out, k)
        out += b": "
        raw(out, m[k], depth + 1)
        if i + 1 < len(keys):
            out += b","
        out += b"\n"
    pad(out, depth)
    out += b"}"

def esc(out, s):
    out += b'"'
    for c in s.encode("utf-8"):
        esc_byte(out, c)
    out += b'"'


def enc_list(out, v, depth, enc):
    if not v:
        out += b"[]"
        return
    out += b"[\n"
    for i, x in enumerate(v):
        pad(out, depth + 1)
        enc(out, x, depth + 1)
        if i + 1 < len(v):
            out += b","
        out += b"\n"
    pad(out, depth)
    out += b"]"


VERDICTS = ["resident", "would-load", "unservable", "not-here", "unparseable", "unauthorised"]


class HostAllowance:
    def __init__(self, **kw):
        self.hosts = kw.get("hosts", [])


class PickRequest:
    def __init__(self, **kw):
        self.model = kw.get("model", "")
        self.fresh = kw.get("fresh", False)
        self.allowed = kw.get("allowed", None)


class Caller:
    def __init__(self, **kw):
        self.user_description = kw.get("user_description", "")
        self.path_description = kw.get("path_description", "")


class Observation:
    def __init__(self, **kw):
        self.caller = kw.get("caller", Caller())
        self.took_ms = kw.get("took_ms", 0)
        self.cache_age_ms = kw.get("cache_age_ms", 0)


class Alias:
    def __init__(self, **kw):
        self.host = kw.get("host", "")
        self.name = kw.get("name", "")
        self.resident = kw.get("resident", False)
        self.servable = kw.get("servable", False)


class Family:
    def __init__(self, **kw):
        self.family = kw.get("family", "")
        self.names = kw.get("names", [])


class ModelsSnapshot:
    def __init__(self, **kw):
        self.observation = kw.get("observation", Observation())
        self.models = kw.get("models", [])


class HostState:
    def __init__(self, **kw):
        self.host = kw.get("host", "")
        self.base = kw.get("base", "")
        self.up = kw.get("up", False)
        self.why = kw.get("why", "")
        self.installed = kw.get("installed", 0)
        self.resident = kw.get("resident", [])
        self.servable = kw.get("servable", False)


class Ask:
    def __init__(self, **kw):
        self.at = kw.get("at", "")
        self.caller = kw.get("caller", "")
        self.user = kw.get("user", "")
        self.model = kw.get("model", "")
        self.family = kw.get("family", "")
        self.verdict = kw.get("verdict", "")
        self.host = kw.get("host", "")


class HostsSnapshot:
    def __init__(self, **kw):
        self.observation = kw.get("observation", Observation())
        self.hosts = kw.get("hosts", [])
        self.doubled = kw.get("doubled", [])
        self.asked = kw.get("asked", [])


class Decision:
    def __init__(self, **kw):
        self.asked = kw.get("asked", "")
        self.family = kw.get("family", "")
        self.verdict = kw.get("verdict", "")
        self.host = kw.get("host", "")
        self.model = kw.get("model", "")
        self.endpoint = kw.get("endpoint", "")
        self.installed_on = kw.get("installed_on", [])
        self.authorised = kw.get("authorised", None)
        self.withheld = kw.get("withheld", [])
        self.loads = kw.get("loads", 0)
        self.why = kw.get("why", "")


class PickResult:
    def __init__(self, **kw):
        self.observation = kw.get("observation", Observation())
        self.decision = kw.get("decision", Decision())


class OARouterModelsArguments:
    def __init__(self, **kw):
        self.fresh = kw.get("fresh", False)


class OARouterHostsArguments:
    def __init__(self, **kw):
        self.fresh = kw.get("fresh", False)


class OARouterPickArguments:
    def __init__(self, **kw):
        self.request = kw.get("request", PickRequest())


class OAServiceFrame:
    def __init__(self, **kw):
        self.version = kw.get("version", 0)
        self.service = kw.get("service", "")
        self.method = kw.get("method", "")
        self.arguments = kw.get("arguments", "")


class OAServiceReply:
    def __init__(self, **kw):
        self.version = kw.get("version", 0)
        self.service = kw.get("service", "")
        self.method = kw.get("method", "")
        self.ok = kw.get("ok", False)
        self.payload = kw.get("payload", "")


class OAServiceError:
    def __init__(self, **kw):
        self.code = kw.get("code", "")
        self.message = kw.get("message", "")


class OARouterModelsResult:
    def __init__(self, **kw):
        self.value = kw.get("value", ModelsSnapshot())


class OARouterHostsResult:
    def __init__(self, **kw):
        self.value = kw.get("value", HostsSnapshot())


class OARouterPickResult:
    def __init__(self, **kw):
        self.value = kw.get("value", PickResult())


def enc_hostallowance(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "hosts")
    out += b": "
    strs(out, v.hosts, depth + 1)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_pickrequest(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "model")
    out += b": "
    esc(out, v.model)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "fresh")
    out += b": "
    out += b"true" if v.fresh else b"false"
    if v.allowed is not None:
        out += b","
        out += b"\n"
        pad(out, depth + 1)
        esc(out, "allowed")
        out += b": "
        enc_hostallowance(out, v.allowed, depth + 1)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_caller(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "user_description")
    out += b": "
    esc(out, v.user_description)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "path_description")
    out += b": "
    esc(out, v.path_description)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_observation(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "caller")
    out += b": "
    enc_caller(out, v.caller, depth + 1)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "took_ms")
    out += b": "
    num(out, v.took_ms)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "cache_age_ms")
    out += b": "
    num(out, v.cache_age_ms)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_alias(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "host")
    out += b": "
    esc(out, v.host)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "name")
    out += b": "
    esc(out, v.name)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "resident")
    out += b": "
    out += b"true" if v.resident else b"false"
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "servable")
    out += b": "
    out += b"true" if v.servable else b"false"
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_family(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "family")
    out += b": "
    esc(out, v.family)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "names")
    out += b": "
    enc_list(out, v.names, depth + 1, enc_alias)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_modelssnapshot(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "observation")
    out += b": "
    enc_observation(out, v.observation, depth + 1)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "models")
    out += b": "
    enc_list(out, v.models, depth + 1, enc_family)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_hoststate(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "host")
    out += b": "
    esc(out, v.host)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "base")
    out += b": "
    esc(out, v.base)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "up")
    out += b": "
    out += b"true" if v.up else b"false"
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "why")
    out += b": "
    esc(out, v.why)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "installed")
    out += b": "
    num(out, v.installed)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "resident")
    out += b": "
    strs(out, v.resident, depth + 1)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "servable")
    out += b": "
    out += b"true" if v.servable else b"false"
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_ask(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "at")
    out += b": "
    esc(out, _write_timestamp(v.at))
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "caller")
    out += b": "
    esc(out, v.caller)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "user")
    out += b": "
    esc(out, v.user)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "model")
    out += b": "
    esc(out, v.model)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "family")
    out += b": "
    esc(out, v.family)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "verdict")
    out += b": "
    esc(out, v.verdict)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "host")
    out += b": "
    esc(out, v.host)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_hostssnapshot(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "observation")
    out += b": "
    enc_observation(out, v.observation, depth + 1)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "hosts")
    out += b": "
    enc_list(out, v.hosts, depth + 1, enc_hoststate)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "doubled")
    out += b": "
    strs(out, v.doubled, depth + 1)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "asked")
    out += b": "
    enc_list(out, v.asked, depth + 1, enc_ask)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_decision(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "asked")
    out += b": "
    esc(out, v.asked)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "family")
    out += b": "
    esc(out, v.family)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "verdict")
    out += b": "
    esc(out, v.verdict)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "host")
    out += b": "
    esc(out, v.host)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "model")
    out += b": "
    esc(out, v.model)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "endpoint")
    out += b": "
    esc(out, v.endpoint)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "installed_on")
    out += b": "
    strs(out, v.installed_on, depth + 1)
    if v.authorised is not None:
        out += b","
        out += b"\n"
        pad(out, depth + 1)
        esc(out, "authorised")
        out += b": "
        enc_hostallowance(out, v.authorised, depth + 1)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "withheld")
    out += b": "
    strs(out, v.withheld, depth + 1)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "loads")
    out += b": "
    num(out, v.loads)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "why")
    out += b": "
    esc(out, v.why)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_pickresult(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "observation")
    out += b": "
    enc_observation(out, v.observation, depth + 1)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "decision")
    out += b": "
    enc_decision(out, v.decision, depth + 1)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oaroutermodelsarguments(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "fresh")
    out += b": "
    out += b"true" if v.fresh else b"false"
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oarouterhostsarguments(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "fresh")
    out += b": "
    out += b"true" if v.fresh else b"false"
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oarouterpickarguments(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "request")
    out += b": "
    enc_pickrequest(out, v.request, depth + 1)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oaserviceframe(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "version")
    out += b": "
    num(out, v.version)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "service")
    out += b": "
    esc(out, v.service)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "method")
    out += b": "
    esc(out, v.method)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "arguments")
    out += b": "
    out += v.arguments.encode("utf-8") if isinstance(v.arguments, str) else v.arguments
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oaservicereply(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "version")
    out += b": "
    num(out, v.version)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "service")
    out += b": "
    esc(out, v.service)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "method")
    out += b": "
    esc(out, v.method)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "ok")
    out += b": "
    out += b"true" if v.ok else b"false"
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "payload")
    out += b": "
    out += v.payload.encode("utf-8") if isinstance(v.payload, str) else v.payload
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oaserviceerror(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "code")
    out += b": "
    esc(out, v.code)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "message")
    out += b": "
    esc(out, v.message)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oaroutermodelsresult(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "value")
    out += b": "
    enc_modelssnapshot(out, v.value, depth + 1)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oarouterhostsresult(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "value")
    out += b": "
    enc_hostssnapshot(out, v.value, depth + 1)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oarouterpickresult(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "value")
    out += b": "
    enc_pickresult(out, v.value, depth + 1)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def encode(v):
    out = bytearray()
    enc_pickrequest(out, v, 0)
    out += b"\n"
    return bytes(out)


_QUOTE, _BACKSLASH, _COLON, _COMMA = 0x22, 0x5C, 0x3A, 0x2C
_LBRACE, _RBRACE, _LBRACK, _RBRACK = 0x7B, 0x7D, 0x5B, 0x5D
_MINUS, _ZERO, _NINE, _DOT, _LOWER_U, _LOWER_N = 0x2D, 0x30, 0x39, 0x2E, 0x75, 0x6E
_UNESCAPE = {0x22: 0x22, 0x5C: 0x5C, 0x2F: 0x2F, 0x62: 0x08,
             0x66: 0x0C, 0x6E: 0x0A, 0x72: 0x0D, 0x74: 0x09}
_DEPTH_LIMIT = 64
_I64_DIGITS = 19


class Refusal(ValueError):
    def __init__(self, word, offset):
        super().__init__("refused: %s at byte %d" % (word, offset))
        self.word = word
        self.offset = offset


class _Reader:
    __slots__ = ("buf", "pos", "depth")

    def __init__(self, buf):
        self.buf = buf
        self.pos = 0
        self.depth = 0

    def refuse(self, word):
        return Refusal(word, self.pos)

    def at(self):
        return self.buf[self.pos] if self.pos < len(self.buf) else 0

    def ws(self):
        while self.pos < len(self.buf) and self.buf[self.pos] in _WS:
            self.pos += 1

    def enter(self):
        self.depth += 1
        if self.depth > _DEPTH_LIMIT:
            raise self.refuse("depth_exceeded")

    def digit(self):
        return _ZERO <= self.at() <= _NINE

    def string(self):
        if self.at() != _QUOTE:
            raise self.refuse("wrong_type")
        self.pos += 1
        out = bytearray()
        while True:
            if self.pos >= len(self.buf):
                raise self.refuse("malformed")
            c = self.buf[self.pos]
            if c == _QUOTE:
                self.pos += 1
                try:
                    return out.decode("utf-8")
                except UnicodeDecodeError:
                    raise self.refuse("bad_string") from None
            if c < 0x20:
                raise self.refuse("bad_string")
            if c == _BACKSLASH:
                self.escape(out)
            else:
                out.append(c)
                self.pos += 1

    def escape(self, out):
        self.pos += 1
        if self.pos >= len(self.buf):
            raise self.refuse("malformed")
        c = self.buf[self.pos]
        self.pos += 1
        plain = _UNESCAPE.get(c)
        if plain is not None:
            out.append(plain)
            return
        if c != _LOWER_U:
            raise self.refuse("bad_string")
        u = self.hex4()
        if 0xDC00 <= u <= 0xDFFF:
            raise self.refuse("bad_string")
        if 0xD800 <= u <= 0xDBFF:
            if (self.pos + 1 >= len(self.buf) or self.buf[self.pos] != _BACKSLASH
                    or self.buf[self.pos + 1] != _LOWER_U):
                raise self.refuse("bad_string")
            self.pos += 2
            low = self.hex4()
            if not 0xDC00 <= low <= 0xDFFF:
                raise self.refuse("bad_string")
            u = 0x10000 + ((u - 0xD800) << 10) + (low - 0xDC00)
        out += chr(u).encode("utf-8")

    def hex4(self):
        if self.pos + 4 > len(self.buf):
            raise self.refuse("bad_string")
        u = 0
        for i in range(4):
            c = self.buf[self.pos + i]
            if _ZERO <= c <= _NINE:
                u = u << 4 | (c - _ZERO)
            elif 0x61 <= c <= 0x66:
                u = u << 4 | (c - 0x61 + 10)
            elif 0x41 <= c <= 0x46:
                u = u << 4 | (c - 0x41 + 10)
            else:
                raise self.refuse("bad_string")
        self.pos += 4
        return u

    def integer(self, low, high):
        c = self.at()
        if c != _MINUS and not _ZERO <= c <= _NINE:
            raise self.refuse("wrong_type")
        negative = c == _MINUS
        if negative:
            self.pos += 1
        if not self.digit():
            raise self.refuse("malformed")
        start = self.pos
        if self.at() == _ZERO:
            self.pos += 1
        else:
            while self.digit():
                self.pos += 1
        if self.at() in (_DOT, 0x65, 0x45) or self.digit():
            raise self.refuse("number_spelling")
        if self.pos - start > _I64_DIGITS:
            raise self.refuse("number_spelling")
        n = int(self.buf[start:self.pos])
        if negative:
            if n == 0:
                raise self.refuse("number_spelling")
            n = -n
        if n < low or n > high:
            raise self.refuse("number_spelling")
        return n

    def boolean(self):
        if self.at() == 0x74:
            self.literal(b"true")
            return True
        if self.at() == 0x66:
            self.literal(b"false")
            return False
        raise self.refuse("wrong_type")

    def literal(self, word):
        if self.buf[self.pos:self.pos + len(word)] != word:
            raise self.refuse("malformed")
        self.pos += len(word)

    def str_list(self):
        if self.at() != _LBRACK:
            raise self.refuse("wrong_type")
        self.enter()
        self.pos += 1
        out = []
        self.ws()
        if self.at() != _RBRACK:
            while True:
                self.ws()
                out.append(self.string())
                self.ws()
                if self.at() != _COMMA:
                    break
                self.pos += 1
        if self.at() != _RBRACK:
            raise self.refuse("malformed")
        self.pos += 1
        self.depth -= 1
        return out

    def raw_map(self):
        if self.at() != _LBRACE:
            raise self.refuse("wrong_type")
        self.enter()
        self.pos += 1
        out = {}
        self.ws()
        if self.at() != _RBRACE:
            while True:
                self.ws()
                if self.at() != _QUOTE:
                    raise self.refuse("malformed")
                k = self.string()
                if k in out:
                    raise self.refuse("duplicate_key")
                self.ws()
                if self.at() != _COLON:
                    raise self.refuse("malformed")
                self.pos += 1
                self.ws()
                out[k] = self.raw_value()
                self.ws()
                if self.at() != _COMMA:
                    break
                self.pos += 1
        if self.at() != _RBRACE:
            raise self.refuse("malformed")
        self.pos += 1
        self.depth -= 1
        return out

    def raw_value(self):
        start = self.pos
        self.skip_value()
        return self.buf[start:self.pos]

    def skip_value(self):
        c = self.at()
        if c == _QUOTE:
            self.skip_string()
        elif c in (_LBRACE, _LBRACK):
            self.skip_container()
        elif c == 0x74:
            self.literal(b"true")
        elif c == 0x66:
            self.literal(b"false")
        elif c == 0x6E:
            self.literal(b"null")
        elif c == _MINUS or _ZERO <= c <= _NINE:
            self.skip_number()
        else:
            raise self.refuse("malformed")

    # An opaque value is validated and carried, never interpreted. Its syntax is
    # the record's own — the same string reader, so an escape, a control byte or
    # a lone surrogate is judged identically at any depth — and what it is free
    # to spell, it keeps: the bytes between these two offsets are what a writer
    # re-emits. A number is walked, never converted, so a value no host type
    # holds survives the reader that carried it.
    def skip_string(self):
        self.string()

    def some_digits(self):
        n = 0
        while _ZERO <= self.at() <= _NINE:
            self.pos += 1
            n += 1
        if n == 0:
            raise self.refuse("number_spelling")

    def skip_number(self):
        if self.at() == _MINUS:
            self.pos += 1
        c = self.at()
        if c == _ZERO:
            self.pos += 1
        elif _ZERO < c <= _NINE:
            while _ZERO <= self.at() <= _NINE:
                self.pos += 1
        else:
            raise self.refuse("number_spelling")
        if self.at() == _DOT:
            self.pos += 1
            self.some_digits()
        if self.at() in (0x65, 0x45):
            self.pos += 1
            if self.at() in (0x2B, _MINUS):
                self.pos += 1
            self.some_digits()

    def skip_container(self):
        opener = self.at()
        shut = _RBRACE if opener == _LBRACE else _RBRACK
        self.enter()
        self.pos += 1
        self.ws()
        seen = set()
        if self.at() != shut:
            while True:
                self.ws()
                if opener == _LBRACE:
                    if self.at() != _QUOTE:
                        raise self.refuse("malformed")
                    k = self.string()
                    if k in seen:
                        raise self.refuse("duplicate_key")
                    seen.add(k)
                    self.ws()
                    if self.at() != _COLON:
                        raise self.refuse("malformed")
                    self.pos += 1
                    self.ws()
                self.skip_value()
                self.ws()
                if self.at() != _COMMA:
                    break
                self.pos += 1
        if self.at() != shut:
            raise self.refuse("malformed")
        self.pos += 1
        self.depth -= 1


def _decode_list(r, elem):
    if r.at() != _LBRACK:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    out = []
    r.ws()
    if r.at() != _RBRACK:
        while True:
            r.ws()
            out.append(elem(r))
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACK:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    return out


def _digits(s, i, n):
    return len(s) >= i + n and all("0" <= s[i + k] <= "9" for k in range(n))


def _date_part(s):
    return (len(s) >= 19 and _digits(s, 0, 4) and s[4] == "-" and _digits(s, 5, 2)
            and s[7] == "-" and _digits(s, 8, 2) and _digits(s, 11, 2) and s[13] == ":"
            and _digits(s, 14, 2) and s[16] == ":" and _digits(s, 17, 2))


def _lexical_timestamp(s):
    """[DEF-G1] rfc3339-wide: what a reader accepts. Any fraction of one to nine
    digits or none, either case of the separators, and a numeric offset."""
    if not _date_part(s) or s[10] not in "Tt":
        return False
    i = 19
    if i < len(s) and s[i] == ".":
        i += 1
        start = i
        while i < len(s) and "0" <= s[i] <= "9":
            i += 1
        if not 1 <= i - start <= 9:
            return False
    if i >= len(s):
        return False
    if s[i] in "Zz":
        return i + 1 == len(s)
    if s[i] not in "+-":
        return False
    return len(s) == i + 6 and _digits(s, i + 1, 2) and s[i + 3] == ":" and _digits(s, i + 4, 2)


def micros_timestamp(s):
    """[DEF-G2] rfc3339-micros: what a writer emits. Exactly six fractional
    digits, upper-case separators, UTC."""
    return len(s) == 27 and _normalized_timestamp(s) == s


def _read_timestamp(r):
    at = r.pos
    s = r.string()
    if not wide_timestamp(s):
        r.pos = at
        raise r.refuse("bad_timestamp")
    return s

def _timestamp_days(y, m):
    if m == 2:
        return 29 if y % 4 == 0 and (y % 100 != 0 or y % 400 == 0) else 28
    return 30 if m in (4, 6, 9, 11) else 31


def _normalized_timestamp(s):
    if not _lexical_timestamp(s):
        return ""
    y, m, d = int(s[:4]), int(s[5:7]), int(s[8:10])
    h, minute, sec = int(s[11:13]), int(s[14:16]), int(s[17:19])
    if not 1 <= m <= 12 or not 1 <= d <= _timestamp_days(y, m) or h > 23 or minute > 59 or sec > 59:
        return ""
    i, fraction = 19, ""
    if s[i] == ".":
        i += 1
        start = i
        while "0" <= s[i] <= "9":
            i += 1
        fraction = s[start:i]
    total = h * 60 + minute
    if s[i] in "+-":
        oh, om = int(s[i+1:i+3]), int(s[i+4:i+6])
        if oh > 23 or om > 59:
            return ""
        offset = oh * 60 + om
        total += -offset if s[i] == "+" else offset
    if total < 0:
        total += 1440
        d -= 1
    elif total >= 1440:
        total -= 1440
        d += 1
    if d == 0:
        m -= 1
        if m == 0:
            y, m = y - 1, 12
        d = _timestamp_days(y, m)
    if d > _timestamp_days(y, m):
        d, m = 1, m + 1
        if m == 13:
            y, m = y + 1, 1
    if not 0 <= y <= 9999:
        return ""
    return "%04d-%02d-%02dT%02d:%02d:%02d.%sZ" % (y, m, d, total // 60, total % 60, sec, (fraction + "000000")[:6])


def wide_timestamp(s):
    return bool(_normalized_timestamp(s))


def _write_timestamp(s):
    result = _normalized_timestamp(s)
    if not result:
        raise Refusal("bad_timestamp", 0)
    return result


def _decode_hostallowance(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = HostAllowance()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "hosts":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.hosts = r.str_list()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def _decode_pickrequest(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = PickRequest()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "model":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.model = r.string()
            elif key == "fresh":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.fresh = r.boolean()
            elif key == "allowed":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.allowed = _decode_hostallowance(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 3 != 3:
        raise r.refuse("missing_field")
    return v


def _decode_caller(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = Caller()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "user_description":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.user_description = r.string()
            elif key == "path_description":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.path_description = r.string()
            else:
                r.skip_value()
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 3 != 3:
        raise r.refuse("missing_field")
    return v


def _decode_observation(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = Observation()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "caller":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.caller = _decode_caller(r)
            elif key == "took_ms":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.took_ms = r.integer(-9223372036854775808, 9223372036854775807)
            elif key == "cache_age_ms":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.cache_age_ms = r.integer(-9223372036854775808, 9223372036854775807)
            else:
                r.skip_value()
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 7 != 7:
        raise r.refuse("missing_field")
    return v


def _decode_alias(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = Alias()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "host":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.host = r.string()
            elif key == "name":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.name = r.string()
            elif key == "resident":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.resident = r.boolean()
            elif key == "servable":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.servable = r.boolean()
            else:
                r.skip_value()
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 15 != 15:
        raise r.refuse("missing_field")
    return v


def _decode_family(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = Family()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "family":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.family = r.string()
            elif key == "names":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.names = _decode_list(r, _decode_alias)
            else:
                r.skip_value()
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 3 != 3:
        raise r.refuse("missing_field")
    return v


def _decode_modelssnapshot(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = ModelsSnapshot()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "observation":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.observation = _decode_observation(r)
            elif key == "models":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.models = _decode_list(r, _decode_family)
            else:
                r.skip_value()
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 3 != 3:
        raise r.refuse("missing_field")
    return v


def _decode_hoststate(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = HostState()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "host":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.host = r.string()
            elif key == "base":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.base = r.string()
            elif key == "up":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.up = r.boolean()
            elif key == "why":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.why = r.string()
            elif key == "installed":
                if seen & 16:
                    raise r.refuse("duplicate_field")
                seen |= 16
                v.installed = r.integer(-9223372036854775808, 9223372036854775807)
            elif key == "resident":
                if seen & 32:
                    raise r.refuse("duplicate_field")
                seen |= 32
                v.resident = r.str_list()
            elif key == "servable":
                if seen & 64:
                    raise r.refuse("duplicate_field")
                seen |= 64
                v.servable = r.boolean()
            else:
                r.skip_value()
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 127 != 127:
        raise r.refuse("missing_field")
    return v


def _decode_ask(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = Ask()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "at":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.at = _read_timestamp(r)
            elif key == "caller":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.caller = r.string()
            elif key == "user":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.user = r.string()
            elif key == "model":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.model = r.string()
            elif key == "family":
                if seen & 16:
                    raise r.refuse("duplicate_field")
                seen |= 16
                v.family = r.string()
            elif key == "verdict":
                if seen & 32:
                    raise r.refuse("duplicate_field")
                seen |= 32
                v.verdict = r.string()
            elif key == "host":
                if seen & 64:
                    raise r.refuse("duplicate_field")
                seen |= 64
                v.host = r.string()
            else:
                r.skip_value()
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 127 != 127:
        raise r.refuse("missing_field")
    return v


def _decode_hostssnapshot(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = HostsSnapshot()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "observation":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.observation = _decode_observation(r)
            elif key == "hosts":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.hosts = _decode_list(r, _decode_hoststate)
            elif key == "doubled":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.doubled = r.str_list()
            elif key == "asked":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.asked = _decode_list(r, _decode_ask)
            else:
                r.skip_value()
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 15 != 15:
        raise r.refuse("missing_field")
    return v


def _decode_decision(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = Decision()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "asked":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.asked = r.string()
            elif key == "family":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.family = r.string()
            elif key == "verdict":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.verdict = r.string()
            elif key == "host":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.host = r.string()
            elif key == "model":
                if seen & 16:
                    raise r.refuse("duplicate_field")
                seen |= 16
                v.model = r.string()
            elif key == "endpoint":
                if seen & 32:
                    raise r.refuse("duplicate_field")
                seen |= 32
                v.endpoint = r.string()
            elif key == "installed_on":
                if seen & 64:
                    raise r.refuse("duplicate_field")
                seen |= 64
                v.installed_on = r.str_list()
            elif key == "authorised":
                if seen & 128:
                    raise r.refuse("duplicate_field")
                seen |= 128
                v.authorised = _decode_hostallowance(r)
            elif key == "withheld":
                if seen & 256:
                    raise r.refuse("duplicate_field")
                seen |= 256
                v.withheld = r.str_list()
            elif key == "loads":
                if seen & 512:
                    raise r.refuse("duplicate_field")
                seen |= 512
                v.loads = r.integer(-9223372036854775808, 9223372036854775807)
            elif key == "why":
                if seen & 1024:
                    raise r.refuse("duplicate_field")
                seen |= 1024
                v.why = r.string()
            else:
                r.skip_value()
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1919 != 1919:
        raise r.refuse("missing_field")
    return v


def _decode_pickresult(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = PickResult()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "observation":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.observation = _decode_observation(r)
            elif key == "decision":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.decision = _decode_decision(r)
            else:
                r.skip_value()
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 3 != 3:
        raise r.refuse("missing_field")
    return v


def _decode_oaroutermodelsarguments(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OARouterModelsArguments()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "fresh":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.fresh = r.boolean()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def _decode_oarouterhostsarguments(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OARouterHostsArguments()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "fresh":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.fresh = r.boolean()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def _decode_oarouterpickarguments(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OARouterPickArguments()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "request":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.request = _decode_pickrequest(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def _decode_oaserviceframe(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OAServiceFrame()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "version":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.version = r.integer(-2147483648, 2147483647)
            elif key == "service":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.service = r.string()
            elif key == "method":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.method = r.string()
            elif key == "arguments":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.arguments = r.raw_value()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 15 != 15:
        raise r.refuse("missing_field")
    return v


def _decode_oaservicereply(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OAServiceReply()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "version":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.version = r.integer(-2147483648, 2147483647)
            elif key == "service":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.service = r.string()
            elif key == "method":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.method = r.string()
            elif key == "ok":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.ok = r.boolean()
            elif key == "payload":
                if seen & 16:
                    raise r.refuse("duplicate_field")
                seen |= 16
                v.payload = r.raw_value()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 31 != 31:
        raise r.refuse("missing_field")
    return v


def _decode_oaserviceerror(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OAServiceError()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "code":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.code = r.string()
            elif key == "message":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.message = r.string()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 3 != 3:
        raise r.refuse("missing_field")
    return v


def _decode_oaroutermodelsresult(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OARouterModelsResult()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "value":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.value = _decode_modelssnapshot(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def _decode_oarouterhostsresult(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OARouterHostsResult()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "value":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.value = _decode_hostssnapshot(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def _decode_oarouterpickresult(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OARouterPickResult()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "value":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.value = _decode_pickresult(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def decode(data):
    r = _Reader(bytes(data))
    r.ws()
    v = _decode_pickrequest(r)
    r.ws()
    if r.pos < len(r.buf):
        raise r.refuse("trailing_bytes")
    return v


# REFUSALS is in the order two of them are chosen between.

REFUSALS = ["malformed", "bad_string", "number_spelling", "wrong_type", "bad_timestamp", "depth_exceeded", "duplicate_key", "duplicate_field", "unknown_field", "missing_field", "trailing_bytes"]


def refusal_rank(word):
    return REFUSALS.index(word) if word in REFUSALS else -1


class DispatchError(ValueError):
    def __init__(self, code):
        super().__init__(code)
        self.code = code


def _service_decode(decoder, frame, depth=0):
    if not isinstance(frame, (bytes, bytearray, memoryview)):
        raise TypeError("transport frame must be bytes")
    r = _Reader(bytes(frame))
    r.depth = depth
    r.ws()
    value = decoder(r)
    r.ws()
    if r.pos != len(r.buf):
        raise r.refuse("trailing_bytes")
    return value


def _service_encode(encoder, value, depth):
    out = bytearray()
    try:
        encoder(out, value, depth)
    except UnicodeError:
        raise Refusal("bad_string", 0) from None
    return bytes(out)


def _service_request(service, method, arguments):
    v = OAServiceFrame(version=1, service=service, method=method, arguments=arguments)
    frame = _service_encode(enc_oaserviceframe, v, 0)
    _service_decode(_decode_oaserviceframe, frame)
    return frame


def _service_check(kind, value, depth=0):
    # Python coercions must not silently change typed service arguments.
    if depth >= _DEPTH_LIMIT and (kind.startswith(("list<", "map<")) or kind in _SERVICE_RECORDS):
        raise Refusal("depth_exceeded", 0)
    if kind == "string":
        valid = type(value) is str
    elif kind in ("i32", "i64"):
        valid = type(value) is int
        if valid:
            limit = 1 << (31 if kind == "i32" else 63)
            if not -limit <= value < limit:
                raise Refusal("number_spelling", 0)
    elif kind == "bool":
        valid = type(value) is bool
    elif kind == "json":
        valid = isinstance(value, (str, bytes, bytearray, memoryview))
    elif kind.startswith("list<"):
        valid = type(value) is list
        if valid:
            for item in value:
                _service_check(kind[5:-1], item, depth + 1)
    elif kind.startswith("map<string,"):
        valid = type(value) is dict
        if valid:
            for key, item in value.items():
                _service_check("string", key, depth + 1)
                _service_check(kind[11:-1], item, depth + 1)
    else:
        cls, fields = _SERVICE_RECORDS[kind]
        valid = isinstance(value, cls)
        if valid:
            for name, field_kind, omit in fields:
                if not hasattr(value, name):
                    raise Refusal("missing_field", 0)
                item = getattr(value, name)
                if omit == "absent" and item is None:
                    continue
                _service_check(field_kind, item, depth + 1)
    if not valid:
        raise Refusal("wrong_type", 0)


class ServiceError(Exception):
    def __init__(self, code, message=""):
        super().__init__(message if message else code)
        self.code = code
        self.message = message


def _service_response(frame, service, method):
    reply = _service_decode(_decode_oaservicereply, frame)
    if reply.version != 1:
        raise DispatchError("unknown_version")
    if reply.service != service or reply.method != method:
        raise DispatchError("mismatched_response")
    if not reply.ok:
        error = _service_decode(_decode_oaserviceerror, reply.payload, 1)
        if not error.code:
            raise DispatchError("invalid_error")
        raise ServiceError(error.code, error.message)
    return reply.payload

_SERVICE_RECORDS = {
    "HostAllowance": (HostAllowance, [("hosts","list<string>","never"),]),
    "PickRequest": (PickRequest, [("model","string","never"),("fresh","bool","never"),("allowed","HostAllowance","absent"),]),
    "Caller": (Caller, [("user_description","string","never"),("path_description","string","never"),]),
    "Observation": (Observation, [("caller","Caller","never"),("took_ms","i64","never"),("cache_age_ms","i64","never"),]),
    "Alias": (Alias, [("host","string","never"),("name","string","never"),("resident","bool","never"),("servable","bool","never"),]),
    "Family": (Family, [("family","string","never"),("names","list<Alias>","never"),]),
    "ModelsSnapshot": (ModelsSnapshot, [("observation","Observation","never"),("models","list<Family>","never"),]),
    "HostState": (HostState, [("host","string","never"),("base","string","never"),("up","bool","never"),("why","string","never"),("installed","i64","never"),("resident","list<string>","never"),("servable","bool","never"),]),
    "Ask": (Ask, [("at","string","never"),("caller","string","never"),("user","string","never"),("model","string","never"),("family","string","never"),("verdict","string","never"),("host","string","never"),]),
    "HostsSnapshot": (HostsSnapshot, [("observation","Observation","never"),("hosts","list<HostState>","never"),("doubled","list<string>","never"),("asked","list<Ask>","never"),]),
    "Decision": (Decision, [("asked","string","never"),("family","string","never"),("verdict","string","never"),("host","string","never"),("model","string","never"),("endpoint","string","never"),("installed_on","list<string>","never"),("authorised","HostAllowance","absent"),("withheld","list<string>","never"),("loads","i64","never"),("why","string","never"),]),
    "PickResult": (PickResult, [("observation","Observation","never"),("decision","Decision","never"),]),
    "OARouterModelsArguments": (OARouterModelsArguments, [("fresh","bool","never"),]),
    "OARouterHostsArguments": (OARouterHostsArguments, [("fresh","bool","never"),]),
    "OARouterPickArguments": (OARouterPickArguments, [("request","PickRequest","never"),]),
    "OAServiceFrame": (OAServiceFrame, [("version","i32","never"),("service","string","never"),("method","string","never"),("arguments","json","never"),]),
    "OAServiceReply": (OAServiceReply, [("version","i32","never"),("service","string","never"),("method","string","never"),("ok","bool","never"),("payload","json","never"),]),
    "OAServiceError": (OAServiceError, [("code","string","never"),("message","string","never"),]),
    "OARouterModelsResult": (OARouterModelsResult, [("value","ModelsSnapshot","never"),]),
    "OARouterHostsResult": (OARouterHostsResult, [("value","HostsSnapshot","never"),]),
    "OARouterPickResult": (OARouterPickResult, [("value","PickResult","never"),]),
}


class Router:
    __doc__ = "Read existing model hosts and choose where a caller may ask. Decisions do not enforce access to hosts outside the router."
    def Models(self, fresh: "bool") -> "ModelsSnapshot":
        raise NotImplementedError
    def Hosts(self, fresh: "bool") -> "HostsSnapshot":
        raise NotImplementedError
    def Pick(self, request: "PickRequest") -> "PickResult":
        raise NotImplementedError


class RouterClient(Router):
    def __init__(self, transport):
        self._transport = transport

    def Models(self, fresh: "bool") -> "ModelsSnapshot":
        _service_check("bool", fresh)
        _oa_args = OARouterModelsArguments()
        _oa_args.fresh = fresh
        _oa_arguments = _service_encode(enc_oaroutermodelsarguments, _oa_args, 1)
        _service_decode(_decode_oaroutermodelsarguments, _oa_arguments, 1)
        _oa_request = _service_request("abstraction.router/router@1", "Models", _oa_arguments)
        _oa_payload = _service_response(self._transport.exchange_frame(_oa_request), "abstraction.router/router@1", "Models")
        _oa_result = _service_decode(_decode_oaroutermodelsresult, _oa_payload, 1)
        return _oa_result.value

    def Hosts(self, fresh: "bool") -> "HostsSnapshot":
        _service_check("bool", fresh)
        _oa_args = OARouterHostsArguments()
        _oa_args.fresh = fresh
        _oa_arguments = _service_encode(enc_oarouterhostsarguments, _oa_args, 1)
        _service_decode(_decode_oarouterhostsarguments, _oa_arguments, 1)
        _oa_request = _service_request("abstraction.router/router@1", "Hosts", _oa_arguments)
        _oa_payload = _service_response(self._transport.exchange_frame(_oa_request), "abstraction.router/router@1", "Hosts")
        _oa_result = _service_decode(_decode_oarouterhostsresult, _oa_payload, 1)
        return _oa_result.value

    def Pick(self, request: "PickRequest") -> "PickResult":
        _service_check("PickRequest", request)
        _oa_args = OARouterPickArguments()
        _oa_args.request = request
        _oa_arguments = _service_encode(enc_oarouterpickarguments, _oa_args, 1)
        _service_decode(_decode_oarouterpickarguments, _oa_arguments, 1)
        _oa_request = _service_request("abstraction.router/router@1", "Pick", _oa_arguments)
        _oa_payload = _service_response(self._transport.exchange_frame(_oa_request), "abstraction.router/router@1", "Pick")
        _oa_result = _service_decode(_decode_oarouterpickresult, _oa_payload, 1)
        return _oa_result.value
